### ISSUE TITLE
Custom Explosions cause no items to drop upon death

### ISSUE THREAD

**Issue by Biochao** [WhiskyTangoFawks/Expedition#101]
While playing I was losing all my items when I died to Creepers. After some testing found out any explosion caused no items to drop.

Turning off "Override explosions with custom explosions" made items drop again.

WTF-Expedition_1.10.2_v-1.4.1

**Comment by WhiskyTangoFawks** [comment]
I suspect it's actually throwing the items around, rather than preventing the drops, as I'm not doing anything with player death- try turning "Explosion entity force percentage modifier" and see if that makes a difference.

**Comment by Biochao** [comment]
I've tested exploding myself in a Bedrock box. Experience drops, but no items.

**Comment by Biochao** [comment]
After some more testing with only WTFExpedition and Tinkers Construct installed it looks like items are getting vaporized when they drop. If you have a nether star it drops just fine because it can not be destroyed by explosions. 
Maybe the items drop before the custom explosions are finished?

**Comment by WhiskyTangoFawks** [comment]
They do drop after each increment of the explosion, looks like they're being damaged somehow (didn't know that was possible).  Once I get the generator overhaul sorted out I'll figure out why this is happening, and stop it.

**Comment by WhiskyTangoFawks** [comment]
I've got this sorted.  Next release will have the fix.
