### ISSUE TITLE
[alpha] NullPointerException at TickGenBuffer.bufferGen()

### ISSUE THREAD

**Issue by ColorYak** [WhiskyTangoFawks/Expedition#103]
Encounted this crash on a test instance while testing out some mods:

https://gist.github.com/ColorYak/bf1abfdf059d4bf8fbcc336f82cbc634

Using the recently uploaded alpha.

**Comment by WhiskyTangoFawks** [comment]
Thanks.  I think that's the same one I've been seeing- I'm pretty sure due to a rare occurance where my mod tries to place a mob spawner, and the game doesn't like the way I'm doing it.  I should have a fix out once I get past the tweaks I'm doing now.

**Comment by WhiskyTangoFawks** [comment]
New beta release should solve this issue.
