### ISSUE TITLE
Starting Game automatically reverts Ore Pitch

### ISSUE THREAD

**Issue by votex09** [WhiskyTangoFawks/Expedition#105]
D:"Average vein pitch (o for horizontal, 1.5 for vertical)"=o
gets reverted to 
D:"Average vein pitch (o for horizontal, 1.5 for vertical)"=1.5

unless file is set to read only.

This causes problems with world gen obviously.
WTF-Expedition_1.10.2_v-1.alpha

**Comment by WhiskyTangoFawks** [comment]
Are you using a non-vanilla launcher?

**Comment by votex09** [comment]
Curse uses the vanilla launcher yes?

**Comment by WhiskyTangoFawks** [comment]
I believe it's a slightly modified on.  But if you're using a curse launcher, then that might be the source of it, although I'm not sure why it would be causing issues.

**Comment by ruyanve** [comment]
Tehee, this is an easy fix and something I totally forgot to mention! :-D

So.. it says o (the letter) for horizontal, in truth it's 0 (the number)...

Tested on curse launcher, works like a charm :-P

**Comment by WhiskyTangoFawks** [comment]
Lol, yes, the pitch is measured in the number of radians.  having a letter there would result in it not working.

**Comment by votex09** [comment]
Actually.... If I put zeros there all the pre generates vertically.

**Comment by ruyanve** [comment]
confirmed for latest alpha
