### ISSUE TITLE
No vanilla trees in roofed forest

### ISSUE THREAD

**Issue by Oxosorrel** [WhiskyTangoFawks/Expedition#11]
Using JUST WTF-Expedition_1.10.2_Beta11.4 (no other mods installed)  

Using Forge build 1.10.2-12.18.1.2086

No dark oak, or other vanilla trees in Roofed Forest Biome. Giant Mushrooms however, do generate.

This occurs when using the setting in WTFOverworldGenConfig.cfg

B:"Use custom big trees instead of default trees"=true 

Setting this to false and vanilla trees to decorate the Roofed Forest Biome, but I assume none of WFT's big tree variants are called, so that is a partial work around.

This is probably be related to a change made in forge on this issue. 
https://github.com/MinecraftForge/MinecraftForge/issues/3215

This change to forge was made on build 1.10.2-12.18.1.2072... rolling forge back to the release before that,  and vanilla trees generate in roofed forest biome when WFT's big tree set to true.

**Comment by WhiskyTangoFawks** [comment]
Yep, that's definitely due to the forge changes.  I had ignoring roofed forest trees because I couldn't cancel them.

I've just finished a massive overhaul on the tree generation routines, so I'll make sure they're good for the next release.

**Comment by Oxosorrel** [comment]
Thanks, keep on rocking, looking forward to the next build.

**Comment by WhiskyTangoFawks** [comment]
Alright, new realease fixes the issue
