### ISSUE TITLE
Wither dies from its own explosion after spawning

### ISSUE THREAD

**Issue by AshyRaccoon** [WhiskyTangoFawks/Expedition#115]
After summoning a wither, once it finishes its spawn-in animation, and explodes, it kills itself every time.

Tested in single player, Minecraft 1.10.2, forge-12.18.3.2239.
I got the same result on a new profile using only WTF-Expedition_1.10.2_v-1.4.1, and release versions of Not Enough Items and its dependencies (JEI, CodeChickenCore, CodeChickenLib)
If I set B:"Override explosions with custom explosions"=false, then it does not kill itself after spawning.

**Comment by Silvrus** [comment]
I was wondering what was causing that. Been happening to me and it drops the nether star with this death as well.

**Comment by WhiskyTangoFawks** [comment]
I've got this issue solved, and the fix will go out with the next release.  If you're wanting to fight the wither this weekend, let me know and I'll push out a hotfix.

**Comment by ate0ate** [comment]
Has this been fixed? I am setting up an automated wither spawner but I'll hold off if not.

**Comment by WhiskyTangoFawks** [comment]
I've fixed it in my dev environment, but not released it yet.  If there's a need for it, let me know and I'll push out a hotfix.

**Comment by ate0ate** [comment]
No no, I have a couple single player worlds I'm playing around with so no rush. I just noticed this while perusing the issues and happen to be mid-build of an automated wither spawner. It can definitely wait. Or I may take advantage of the temporarily easy to obtain wither stars:)
Thanks!

**Comment by WhiskyTangoFawks** [comment]
new release is out
