### ISSUE TITLE
Odd world gen issues in Wtf Expedition -v1.10.2_1.5Beta5

### ISSUE THREAD

**Issue by ate0ate** [WhiskyTangoFawks/Expedition#118]
On several occasions now, when starting a new single player world, I've noticed a pretty bizarre issue with world generation. It seems like sometimes Expedition's world gen can't keep up in certain biomes, particularly near dense vanilla forests or BoP redwood forests, and I notice that there are no stalactites/stalagmites in caves, the trees are small vanilla trees, and I don't see any mossy variants of blocks or water puddles that expedition adds. After digging a quick hobbit hole and clearing out some trees I shut down the game and exited. After relaunching and opening the world again all of a sudden Expedition's world gen kicks in and replaces the vanilla trees with the Expedition ones, decorates my hand dug hobbit hole with stalactites and even throws water puddles on top of my crafting table.

http://imgur.com/a/ydqxD

This only happens upon this first world load and doesn't seem to occur again. It seems like for whatever reason the Expedition gen gets overwhelmed and cannot run but kicks in after exiting the game and restarting. Definitely an issue at times. My once barren and cleared terrain is now full of massive trees and there's water dripping into puddles all over my base lol. This is all using forge 12.18.3.2254. Thanks!

**Comment by WhiskyTangoFawks** [comment]
I've had to add another layer of delay to my mods chunk decoration.  There is a noticeable delay in chunk population, but not enough that you should be seeing this problem.  And yes, it rechecks things when reloading chunks, so rejoining the world would cause the generation to catch up on things it previously missed if there was a failure.

My first suspicion is that another mod is interfering, calling for generation of extra chunks, and that is overwhelming my generator.  Is this part of a large modpack?

  You might also be able to find some clues as to what's happening in the game log.  When my mod can't generate a chunk, it spits out an error message.

**Comment by ate0ate** [comment]
Yes, its a considerably large personal modpack, not too dissimilar from the All the Mods pack. I do use foamfix, if that effects things, and very recently added thermal expansion/foundation and Astral Sorcery. I will investigate the logs to see if there is anything notable and attempt to narrow down which mod may be causing the issue. Thank you much for your time.

**Comment by WhiskyTangoFawks** [comment]
My personal pack is 40 mods or so, and I'm not seeing this issue, so if you're on a large pack, my suspicion is a conflict.  Do any of the mods cause generation of large things, which are likely to bleed into adjacent chunks on a regular basis (large structures, big trees, etc)?

In the meantime- as you found simply reloading the world more or less solves the issue.  So, as a work around, you can just do that.

**Comment by ate0ate** [comment]
I just checked quite a few logs and nothing about generation is mentioned. The only thing I noticed at all is some server can't keep up notifications when Aroma Backup runs to save my world but that's it. I do have a fairly good rig with 16G of ram and GTX980 but I still lag slightly whenever Aroma Backup runs.

The only mods I know of that generate anything of significance is Roguelike Dungeons, Natura, and Biomes O Plenty. I first noticed this issue in their redwood forest which is ridiculously full of giant trees. Astral Sorcery adds very small ruins structures here and there. I'm not sure what Thermal Foundation actually does or does not generate other than their ore.

I also have been flying around in creative looking for a good starting point and covering vast distances quickly with a view distance set at 16 chunks. This is when the Expedition generation most noticeably fails. It looks like it completely stops working and whole biomes generate with vanilla trees and such. At this point I can start base building, go mining, whatever and Expedition gen never seems to run no matter how long I play. As soon as I reload after exiting, boom, Expedition terrain gen kicks in. Its not a big deal to me really since it seems to be fixed after restarting, it just seemed like something worth mentioning. I'll keep messing around and checking my logs just in case, but I suspect I'm just throwing too much at Minecraft. Thanks a lot for looking into this.

**Comment by WhiskyTangoFawks** [comment]
yeah, flying around at top speed with view distance 16 will overload the generator, you've just got a massively backed up tick buffer.  It should catch up eventually, but I do have it set to only handle one chunk per tick, in an effort to minimise lag.  I'm suprised it's breaking completely though.  I'll leave the issue open to remind myself to check in on this periodically.  The work around is simple though, just save and quit, and reload the world once you've found a spot you like.
