### ISSUE TITLE
'tile.genMarker.name' Generates in void worlds

### ISSUE THREAD

**Issue by Biochao** [WhiskyTangoFawks/Expedition#119]
Tested with [Simple Sky Block](https://github.com/Adversarius13293/SimpleSkyBlock) and [Botania Garden of Glass](https://minecraft.curseforge.com/projects/botania-garden-of-glass) world generators.
In the config there are no ores set to generate in dimension 0. I'd like to keep WTF Ore Generation on so I can have dense ores in the Nether.

![2017-03-07_13 15 21](https://cloud.githubusercontent.com/assets/6515654/23671885/daf48732-033a-11e7-8765-79746c6ee7c3.png)
![2017-03-07_13 27 53](https://cloud.githubusercontent.com/assets/6515654/23671886/daf7c172-033a-11e7-9dd9-eac1d37672d6.png)

**Comment by Biochao** [comment]
It also happens in the End.
![2017-03-07_13 54 44](https://cloud.githubusercontent.com/assets/6515654/23672747/b08906f0-033d-11e7-8264-782a2e537731.png)

**Comment by WhiskyTangoFawks** [comment]
It shouldn't be generating in sky-type worlds.  It's just a marker I place, to keep track of chunks that have generated, but my mod hasn't handled yet.  I'll look into it, and get it sorted.

**Comment by WhiskyTangoFawks** [comment]
New release is out that *should* fix this issue...

**Comment by Biochao** [comment]
Looks like it does. Thanks!
![2017-03-08_23 29 10](https://cloud.githubusercontent.com/assets/6515654/23735978/2eb63042-0457-11e7-89bb-f5abe23d13ce.png)
