### ISSUE TITLE
Crashed with new update

### ISSUE THREAD

**Issue by mindcloud69** [WhiskyTangoFawks/Expedition#12]
WTF-Expedition_1.10.2_Beta12.1.jar

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: rtg/world/gen/feature/tree/rtg/TreeRTG

https://gist.github.com/mindcloud69/ab098b39aeb2272f271ae5fbc3479c3f

**Comment by WhiskyTangoFawks** [comment]
I forgot to test it without RTG, so it's looking for the import.

As an immediate fix if you want to use the mod now, you can download RTG and just not use the world type.

I'll try and get the import for it sorted tomorrow so that isn't necessary though.

**Comment by mindcloud69** [comment]
Thanks.

**Comment by WhiskyTangoFawks** [comment]
Update just went out with the fix
