### ISSUE TITLE
Some blocks can't be placed in gamemode 0

### ISSUE THREAD

**Issue by megaloloful** [WhiskyTangoFawks/Expedition#123]
I somehow can't place some blocks (like stone for example) when I'm in gamemode 0. It works in gamemode 1 somehow though..

**Comment by WhiskyTangoFawks** [comment]
You've added them to the ore list.  Ores cannot be placed in world, this is to prevent repeat fracturing by mining an ore, placing it, mining again, placing it again, etc.
