### ISSUE TITLE
Request - Support for Digimobs 1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [WhiskyTangoFawks/Expedition#126]
https://gist.github.com/P3rf3ctXZer0/4ea3f2a9f0cf3ea8b4f3609f20f1a3f5

**Comment by P3rf3ctXZer0** [comment]
The creator of digimobs does not tend to be very understanding of other mods. Since I know you I thought maybe you could whip up some type of change on your end. It would mean a lot to me. Even if you simply disable digimob support. If it helps digimobs is limited to its own plane of existance. The default dimensional id is "8"

**Comment by WhiskyTangoFawks** [comment]
I've got one thing which might solve the issue.  Will try to get a new release out later today for testing

**Comment by P3rf3ctXZer0** [comment]
Thanks again fawks :)

**Comment by WhiskyTangoFawks** [comment]
IThe 1.5 release has what should be a fix for this.  If it's not fixed, then there's nothing I can do on my end.
