### ISSUE TITLE
Retrogen Upon Reentering Worlds

### ISSUE THREAD

**Issue by Darkosto** [WhiskyTangoFawks/Expedition#127]
When players enter a world in SP, on occasion, it looks like there's a retrogen of certain decoration blocks. This has been known to replace some player's chests and other important blocks in their base. Is it possible this could be looked at?

WTF Version: v1.5Beta1
Forge: 2254
MC: 1.10.2

Thank you!
Darkosto

**Comment by WhiskyTangoFawks** [comment]
I'm aware of the issue.  What I've seen is that this occurs primarily after a player has been flying around in creative mode fairly extensively, or done something else to cause the generation of very large areas, in a pack with reasonably heavy chunk generation to start with.  This can break my world gen buffer, which results in chunks not being decorated by my mod.  When the chunk is next loaded (e.g. when a player saves and exists and reloads), it checks, sees that generation isn't complete, and completes it.

As a work around, if a player notices trees from my mod not generating, they needs to save and exit, and reload before stopping and building.

In the long run, I do hope to fix the issue.  However, in the short term, this is actually improved behaviour from earlier versions, which tended to crash under similar circumastances.

**Comment by WhiskyTangoFawks** [comment]
the 1.5 release should solve this issue.
