### ISSUE TITLE
Falling Block/Stone Lava Crust Block with big fps lag

### ISSUE THREAD

**Issue by ShaCraft** [WhiskyTangoFawks/Expedition#13]
Stone Lava crust drops FPS form 230+ down to 20-30 FPS. When you try to mine them they show Falling Block till you restart the client. 
![2016-09-20_13 37 16](https://cloud.githubusercontent.com/assets/13075796/18681873/e78f3884-7f37-11e6-8cd3-b668da967796.png)
![2016-09-20_13 37 30](https://cloud.githubusercontent.com/assets/13075796/18681885/eff9c2e6-7f37-11e6-9858-f32535f34ab7.png)

**Comment by WhiskyTangoFawks** [comment]
I've actually just been working on this one.  Fix should be out with the next update- hopefully sometime before the weekend.

**Comment by WhiskyTangoFawks** [comment]
Fixed in Beta13.
