### ISSUE TITLE
Gameplay Client Crash on Load

### ISSUE THREAD

**Issue by Darkosto** [WhiskyTangoFawks/Expedition#131]
I just updated everything to the latest versions and picking up the newer gameplay tweaks. I'm getting a crash during client startup/load

https://pastebin.com/2xffZczL

MC: 1.10.2
Forge: 2254
Expedition v1.5.1
Gameplay: 1.0

Hopefully, this is not something incorrect on my end. 

Thank you!
Darkosto

**Comment by WesCook** [comment]
Not just you.  Same issue here, with freshly generated configs.

**Comment by WhiskyTangoFawks** [comment]
I removed the gameplay tweaks config option from expedition, and because I was half asleep didn't catch that I'd obviously need to update the things in the GameplayTweaks mod that still were connected to this.

Uploading the fix now.

**Comment by ghost** [comment]
Interesting. While waiting/refreshing for the upload I was able to archive older versions. http://i.imgur.com/Q7Bz8Fn.jpg

Game is loading up correctly now.
