### ISSUE TITLE
Crash while exploring

### ISSUE THREAD

**Issue by Kiyaku** [WhiskyTangoFawks/Expedition#14]
Was just running around, creating new chunks and then eventually crashed with this:
http://pastebin.com/uKn51C2q

Not sure why this crash log didnt list all the mods and such, but this is my current list: http://pastebin.com/SjgtrDnp
I chose the Realistic Terrain Gen (version 4.1.1.2-snapshot 7).

Version beta 13 of your mod
using forge 2094

Let me know if i can provide anything else to help out!

**Comment by WhiskyTangoFawks** [comment]
That is very strange...

Has this happened once, or are you able to repeat it with the same seed?  Does it happen on different seeds with the same pack?

**Comment by Kiyaku** [comment]
So i tried to load the world that crashed, to see if it happens again or just the first time it tries to gen the chunk. Loading it seemed to work fine, it hasn't crashed since. 

Then i tried to Re-Create the same world, went to the same spot, and got the same crash again. However, i tried this a few times and this was the only time i could re-create it. 

I almost feel like it only happens if you play on a world, exit that world and then make a new one. Been seeing a lot of similar crashes with others mods where exiting and loading/creating a new world. 

I'll keep testing this more! 

On a side note, this some of the ice cave stuff that generated, it put several layers of ice on top of each other: https://dl.dropboxusercontent.com/u/1658875/Minecraft/2016-09-23_13.58.52.png

**Comment by WhiskyTangoFawks** [comment]
I've got the ice sorted for the next release.

The fact that your seeing similar crashes with other mods suggests that it isn't an issue with my mod, which is backed up by the crash log.  It doesn't make a lot of sense that my mod would be the source of the problem, as it's in the block update tick, and if that was a problem you'd expect it to be crashing a LOT more often.

**Comment by WhiskyTangoFawks** [comment]
Any chance this is related to going into another dimension?

**Comment by Kiyaku** [comment]
It was in the overworld and i hadn't visited any other dimension in that save file. 
I can't really reproduce it anymore either unfortunately. I still think it has to do with loading a world -> exiting -> loading another world, so unlikely that the mod itself causes it. But even testing that for a while didn't make it crash. 

Probably can be closed then heh, but i'll definitely let you know when it happens again. 

However, i was gonna make a new ticket about a different issue, the anti-pillar thing doesn;t seem to work in the latest version anymore, i can pillar as far as i want without anything collapsing (deleted configs, double checked the setting). Works fine in the previous version. If you want i'll make a new ticket, i also recorded it just in case.

**Comment by WhiskyTangoFawks** [comment]
yeah, that's a bug.  I'll get it sorted for the next release.
