### ISSUE TITLE
Fracturing Stone to cobblestone isn't SMP compatible

### ISSUE THREAD

**Issue by LemADEC** [WhiskyTangoFawks/Expedition#15]
As of WTF_Expedition_1.10.2_Beta13, in SMP, players are unable to break stone.
In SSP, players are able to break stone into cobblestone.

**Comment by WhiskyTangoFawks** [comment]
I've tested this on single player, single player world opened to multiplayer, and on a server, and am unable to replicate this issue.  Can you be a bit more specific on how you got this to occur?  Also, try deleting and regenerating the WTFGameplay config, in case it's gotten screwed up along the way.

**Comment by LemADEC** [comment]
it was default configuration of the mod. We are using Sponge on the server, so it might be some ASM conflict.

**Comment by LemADEC** [comment]
Here's the related server configuration:
```
mining {
    S:"Mining speed modifiers"==minecraft:stone@1,minecraft:sandstone@1
    B:"Modify hammer behaviour"=true
    B:"Ores fracture adjacent blocks when mined"=true
    S:"Ores to add for fracturing- modname:blockname"=minecraft:emerald_ore
    B:"Stone fractures before breaking"=false
}
```

With this setup, I've noted several issues:
1- WTF iron ore doesn't fracture nearby stone.
2- Vanilla emerald ore will not fracture nearby stone.
3- WTF iron ore requires to be mined twice. There's no hint on client side of this double mining requirement, which is confusing.
Reconnecting to the server doesn't show the fracture effect.

**Comment by WhiskyTangoFawks** [comment]
I've tested all of this, and I'm unable to replicate any of them, it is all working fine on my end.  

My suspicion is that these are related to the fact that you're running sponge, but I'm not familiar with it, or how sponge-forge would interact with my mod in the slightest.  I've definitely not built against it though, so this may be the problem.

There's one possibility that changing the client config but not the server config could cause these issues, but if you're running the defaults on both, then it shouldn't be the cause.

**Comment by LemADEC** [comment]
Sponge use "mixins" to modify the base classes. If you use ASM instead, there's chance one will overwrite the other.
SpongeForge is just a mod you add to your mod folder, it might even work in SSP.

Without Sponge installed, fracturing nearby stone works when breaking emerald ore.
Also, WTF Coal ore gives coal at each stage now, which makes more sense.
However, WTF Coal ore at its last stage will only fracture in the corners instead of right next to each faces:
![image](https://cloud.githubusercontent.com/assets/4776032/18808641/9370944a-8267-11e6-938a-57ee9eccd526.png)

**Comment by WhiskyTangoFawks** [comment]
I'm not modifing base classes at all- everything works off of the forge event system, so that's what Sponge is interfering with for the stone fracturing.  So, that's a sponge bug for their devs to sort out.

Not a clue how you noticed the coal only fracturing corners, but yep, that was a bug.  It's fixed for the next release.
