### ISSUE TITLE
Trying to build your source.

### ISSUE THREAD

**Issue by frakier** [WhiskyTangoFawks/Expedition#151]
Wanted to try building you mod, well run in a IDE anyway, why? I'm learning is the simplest answer.
Was not sure how else to contact you, if this is out of line feel free to delete.
Either way thanks for you time and the great mod.

Using your source and UndergroundBiomesConstructs1.10
I got the two required libraries[mods] for ic2 and rtg
Used the forge-1.10.2-12.18.3.2234 to build the projects folder
Set everything up and Opened in Eclipse
All the errors reported by eclipse were resolved after importing libraries/dependent project.
When I tried running I get an error... Probably something simple I am missing.

Initializing game
java.lang.NullPointerException: Initializing game
	at exterminatorjeff.undergroundbiomes.client.UBOreModel.bake(UBOreModel.java:69)

[crash-2018-03-26_18.51.23-client.txt](https://github.com/WhiskyTangoFawks/Expedition/files/1849808/crash-2018-03-26_18.51.23-client.txt)
[fml-client-latest.log](https://github.com/WhiskyTangoFawks/Expedition/files/1849810/fml-client-latest.log)

**Comment by WhiskyTangoFox** [comment]
That's an error with underground biomes. Try grabbing an earlier version maybe, based on the message it looks like zeno's done something with the model bake process which eclipse isn't happy with.

**Comment by frakier** [comment]
Thanks
