### ISSUE TITLE
Glitched Stalagmite Base Texture

### ISSUE THREAD

**Issue by WenXin20** [WhiskyTangoFawks/Expedition#19]
All the Stalagmite Base blocks have a glitched model.
![2016-09-29_14 24 10](https://cloud.githubusercontent.com/assets/12000593/18968869/6d72f4b2-8650-11e6-9865-b996759ca1f4.png)

**Comment by WhiskyTangoFawks** [comment]
The later release should have fixed this.  Let me know if you're still seeing this issue.

**Comment by WenXin20** [comment]
I'm still seeing it.

**Comment by WhiskyTangoFawks** [comment]
Can you be a bit more specific as to what you're talking about?  I can't really tell from the pictures, and looking at it up close in game I can't find anything wrong with it.

**Comment by WenXin20** [comment]
There is a a thin line on one side of the model where I can see into the stalagmite, it looks like maybe one of the parts of the model doesn't have the right dimensions.

**Comment by WenXin20** [comment]
On a side note, when I logged back into the game, the stalagmite model had rotated directions and the glitched part appeared on a different side.
