### ISSUE TITLE
May I include this in my modpack?

### ISSUE THREAD

**Issue by majix560** [WhiskyTangoFawks/Expedition#26]
May I include this in my modpack?
You set the license as "All rights reserved unless explicitly stated otherwise" in curse forge.
You didn't set a different license anywhere else.
And you don't explicitly give permission to include in modpacks.

I can not accept the default license that came with the forge MDK as being your mods license as it is completely un-changed from the forge mdk download.

**Comment by WhiskyTangoFawks** [comment]
Yes. The policy should be on the minecraft forum post, I should probably update curse.
