### ISSUE TITLE
Crash with ores for fracturing added

### ISSUE THREAD

**Issue by ulkunderscore** [WhiskyTangoFawks/Expedition#27]
The game crashes on startup when I try to add more than one ore for fracturing.

This worked:
`S:"Ores to add for fracturing- modname:blockname"=immersiveengineering:ore`

This crashed:
`S:"Ores to add for fracturing- modname:blockname"=immersiveengineering:ore, forestry:resources, railcraft:ore`
[Crash Report](http://pastebin.com/76093iwi)

I ran into the same problem when I tried to add the Immersive Engineering Ores one by one a few weeks ago, that's why I assume it has to do with the amount of ores added.

**Comment by WhiskyTangoFawks** [comment]
No, the issue should be that you have the block registry name incorrect, it's nothing to do with the number of ores added.  You need to use the block registry name- which you can get by turning the name getter on in the wtfcore config, and jumping into a game in creative mode and placing the block.

I'll add a more descriptive error message for the next release.

**Comment by ulkunderscore** [comment]
I double checked and the registry names were correct, however I had an empty space behind the comma which apparently is read as well. Now it works.

**Comment by ShadowDrakken** [comment]
It will also have the same crash if the fracturing list is blank

**Comment by charlesbevans** [comment]
Can you also make it not crash when it doesn't recognize a name. I can't see why it doesn't recognize a name without loading. A chat on load or a popup to warn users should be sufficient to go search the logs for all failed registries.
Thank you.
