### ISSUE TITLE
Block-state ore texture overlay is glitchy

### ISSUE THREAD

**Issue by majix560** [WhiskyTangoFawks/Expedition#29]
The block-state ore texture overlay is glitchy.
It near-constantly flashes between being visible, and not being visible, while I'm moving.
While seemingly stabilizing at it's current state when I stand still, even if that state is not being visible.
Also, the custom ore texture overlay just flat out doesn't work in my inventory.
This seems to only happen with block-state ore textures.
Maybe it's glitchy like this because the mod tells forge to put all of the block-state "layers" on the same actual layer in the texture?
However I'm just pulling a guess out of my rear on that one.
[Logs.zip](https://github.com/WhiskyTangoFawks/Expedition/files/559554/Logs.zip)
[Screenies.zip](https://github.com/WhiskyTangoFawks/Expedition/files/559555/Screenies.zip)

**Comment by WhiskyTangoFawks** [comment]
The blocks are a bit glitchy in world if you don't have optifine installed, I recommend doing so if you don't yet have it.  And while I'm aware of the issues with the blocks in inventory, the only way to obtain the blocks as inventory items is in creative, and so I'm not all that worried about it.

**Comment by ShadowDrakken** [comment]
Optifine has been historically bad news. It breaks a lot of mods and is just generally unfriendly to Forge. Hence why most modders refuse to address bugs if Optifine is installed.

**Comment by WhiskyTangoFawks** [comment]
New release version has the default set to simple blockstates which shouldn't have the z-fighting issue, and the fancy blockstates are a config option to enable.
