### ISSUE TITLE
Stone only turns into cobble if custom explosions are enabled + Custom explosions are extremley laggy

### ISSUE THREAD

**Issue by Kiyaku** [WhiskyTangoFawks/Expedition#3]
Forge: 2076
Latest 1.10.2 mod version (beta 10)

If i turn off custom explosions, and mine stone, it just drops cobblestone. If i leave custom explosions on, stone turns into cobbllestone blocks like they are suppose to. 

Using even 1 TNT next to cobblestone will freeze the game for several seconds. Using a couple of TNT at the same time just locks up the game. 

I'm also getting following logs when i detonate TNT with custom explosions enabled:
```
[22:00:50] [Server thread/INFO] [STDOUT]: [wtf.gameplay.GamePlayEventListener:explosion:173]: null (-67.50999999046326, 65.0612500011921, 270.60831592405185) 4.0
[22:00:57] [Server thread/INFO] [STDOUT]: [wtf.gameplay.GamePlayEventListener:explosion:173]: null (-66.49000000953674, 62.06125000119209, 268.50999999046326) 4.0 
```

Let me know if i can provide anything else that would help!

-SC

**Comment by WhiskyTangoFawks** [comment]
I've tested both issues you mention, and they work fine for me.  Double check that your config settings are what you think they are, if you've updated from a previous version I recommend deleting your configs, and letting them regenerate, as during the beta I've been reworking them quite a bit.

The lag with TNT sounds most like you're running a large modpack on a computer that isn't powerful enough for it, or that you have another mod installed that's trying to do something with explosions.

**Comment by Kiyaku** [comment]
I made a completely new instance with just this mod, nothing else (except for forge of course). All configs were default.
My PC is pretty powerful too.

Made a video to show it off a bit better, hopefully: https://youtu.be/odGYZ0KeihA

**Comment by WhiskyTangoFawks** [comment]
That helped a lot.  Thanks.

So- the exploding cobblestone issue isn't really anything to do with explosions- it's to do with creating too many entities (falling block is an entity- stone fracturing inherently drops the block).  I'll need to recode how it detects whether a block should drop during an explosion, instead of just always dropping it to fix that issue- shouldn't be too hard to fix- I just need to be a bit more careful about how I'm calling my gravity checks.

For the explosion setting affecting stone fracturing... I'm still stumped.  I can't reproduce the issue, and there's no way I can see in the code for that to happen...

**Comment by Kiyaku** [comment]
Glad the video was helpful! 

Very odd that the stone thing is working properly for you. I can check with some previous versions if it's any different (it definitely was working properly for me at one point with previous versions).

**Comment by WhiskyTangoFawks** [comment]
Latest release fixes the explosion lag.  Still haven't been able to reproduce other issue.

**Comment by Kiyaku** [comment]
Yep explosion fix AND the stone -> cobble when explosions are turned off are working in this version, woot! 

I guess it must have been that one version only that caused some issues (for me, somehow). Oh well. 

Thanks for fixing it! :)

**Comment by WhiskyTangoFawks** [comment]
I still don't know what was causing that, or what I did to fix it.  You weren't the only person to report it, but I was never able to replicate the issue.  Glad it's working though.
