### ISSUE TITLE
JEI compatibility issue

### ISSUE THREAD

**Issue by mankra** [WhiskyTangoFawks/Expedition#32]
Forge version: 12.18.2.2120
WTF's Expedition version: 1.1
JEI version: 3.13.2.360

The Acacia Roots are missing their texture in the JEI item list.

**Comment by WhiskyTangoFawks** [comment]
It's a JEI issue, the item just doesn't have an inventory texture for reasons that have eluded me since I made the damn thing.  Otherwise it works fine, and it's only noticeable in creative otherwise.

**Comment by mankra** [comment]
It's ok, I put these items on the blacklist as they usually shouldn't be on the JEI list.
