### ISSUE TITLE
Issue - Ghost Blocks on Client while on Server

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [WhiskyTangoFawks/Expedition#35]
I spent the last 2 months trying to figure out why I am getting ghost blocks on my server and after a long time of looking it appears as though I figured something out. Your cracked stone is doing something weird and even more weird when you play for a while ... Anyways re logging
![2016-11-15_11 44 50](https://cloud.githubusercontent.com/assets/10351221/20317065/27f51dc6-ab2a-11e6-8cda-ac10eec6c964.png)
![2016-11-15_11 44 55](https://cloud.githubusercontent.com/assets/10351221/20317069/2b583818-ab2a-11e6-94ff-b7ad0832d9f9.png)
![2016-11-15_11 44 55_2](https://cloud.githubusercontent.com/assets/10351221/20317071/2d07c462-ab2a-11e6-912c-7fdece2183eb.png)
![2016-11-15_11 45 02](https://cloud.githubusercontent.com/assets/10351221/20317077/30e0450a-ab2a-11e6-9631-0bea47e5a03f.png)
![2016-11-15_11 45 04](https://cloud.githubusercontent.com/assets/10351221/20317082/328829b8-ab2a-11e6-9bea-044bc29301bf.png)
![2016-11-15_11 46 48](https://cloud.githubusercontent.com/assets/10351221/20317083/340f3006-ab2a-11e6-81e5-92fe29d7bed3.png)
![2016-11-15_11 47 40](https://cloud.githubusercontent.com/assets/10351221/20317086/354fcd0e-ab2a-11e6-868b-104ac14cba27.png)

![2016-11-15_11 44 59](https://cloud.githubusercontent.com/assets/10351221/20317074/2ee49224-ab2a-11e6-8860-337ff28b4c75.png)

 client side or jumping out of the server and back in seem to fix it. 

https://gist.github.com/P3rf3ctXZer0/00ff8a4af5f320f5ba8ccb09888eee62

**Comment by P3rf3ctXZer0** [comment]
Hope this helps deal with some player anguish!

**Comment by WhiskyTangoFawks** [comment]
Yeah, the falling entities aren't setting back to blocks correctly.  I've not had a chance to deal with it yet.

**Comment by P3rf3ctXZer0** [comment]
Well glad I discovered the cause XD

**Comment by charlesbevans** [comment]
Maybe set a self destruct. If they don't land after 30 seconds, have them disappear or turn into items or something. It's a bandaid, but it should work.

**Comment by WhiskyTangoFawks** [comment]
I've got this one fixed in my dev environment.  Just finishing up UBC compatability before the release.  Should have a new version out before the weekend.

**Comment by P3rf3ctXZer0** [comment]
Nice :)

**Comment by charlesbevans** [comment]
Great! I've got a bunch of falling blocks blocking my lava lake.

**Comment by P3rf3ctXZer0** [comment]
Just re-log it fixes it XD

**Comment by charlesbevans** [comment]
Wow, he fixed it without a patch. Spooky. 😄

**Comment by P3rf3ctXZer0** [comment]
@charlesbevans "client side or jumping out of the server and back in seem to fix it." a quote from me.

**Comment by charlesbevans** [comment]
Nope. It's black magic of the darkest sort. You sir, are a witch that has been consorting with zombie pigmen.
