### ISSUE TITLE
Leaves of big trees decay after update

### ISSUE THREAD

**Issue by cdfa** [WhiskyTangoFawks/Expedition#38]
The trees in this mod are awesome, but when 1 leaf block gets an update, all the trees in a whole forest (espescially roofed forest) can lose their leaves because they are to far away from a wood block. And when it is done the tree top looks awful an jagged. Best fix i could think of is increasing the distance leafs can be away from a wood block before decaying.

**Comment by WhiskyTangoFawks** [comment]
Yeah, that's on my list of things to look into.  Increasing the distance is what I plan to do, it's just a matter of how to do it.

**Comment by b0b123456** [comment]
Any luck on this front? I absolutely love the beautiful forests created by this mod, but the lag from all the leaf decay is making the game unplayable :(

**Comment by WhiskyTangoFawks** [comment]
I've looked into it, but the basic problem is that fixing this require messing with a vanilla class.  Which requires either a substitution alias (which is a system forge never got working 100%) or ASM (and I don't know how to write bytecode).

So, I'm still working on it.  In the meantime I might just set the blocks to not update as an temporary fix.

**Comment by WhiskyTangoFawks** [comment]
I've just uploaded a version with a modified leaf check routine.  See the changelog for details, just be aware that the feature is still experimental, and while it works fine with RTG worlds and my trees, it will break vanilla trees.  It's disabled by default, enable it in the overworld gen config.

**Comment by cdfa** [comment]
That sadly doesn't really fix the problem for me, because i use Terrain Control worlds and they just have vanilla leaves.

**Comment by WhiskyTangoFawks** [comment]
The replacement I use actually replaces vanilla leaves in the game registry.  It doesn't work with vanilla trees because the way they're coded prevents registry substitution of them.  Terrain Control worlds should be compatible with the strategy I'm using if they bypass the vanilla tree generators.  What you'll see if it isn't compatible is a bunch of leafless trees.

**Comment by cdfa** [comment]
well i see a bunch of leafless trees, so no bypassing of the vanilla tree generators i guess
