### ISSUE TITLE
Issue with multiplayer server crash

### ISSUE THREAD

**Issue by Johnvista64** [WhiskyTangoFawks/Expedition#39]
[crash-2016-12-02_01.18.03-server.txt](https://github.com/WhiskyTangoFawks/Expedition/files/626565/crash-2016-12-02_01.18.03-server.txt)

**Comment by srs-bsns** [comment]
@WhiskyTangoFawks, this is related to #23. Did you ever release a new version with the null check that I suggested?

**Comment by WhiskyTangoFawks** [comment]
I'll have a look at this some time today, doing a bug pass, so I'll see what I can do.

**Comment by WhiskyTangoFawks** [comment]
This should be resolved.  And just in case it isn't I've added a try catch to where I'm dealing with RTG to at least prevent the crash.
