### ISSUE TITLE
Dense Cobalt and Ardite are Swapped

### ISSUE THREAD

**Issue by WesCook** [WhiskyTangoFawks/Expedition#40]
In the nether, dense cobalt and ardite ores pop out the wrong type of ore.  Cobalt veins pop out ardite, and vice versa.

I've tried to tweak the ore metadata in the config file but changes don't seem to have any effect.  Standard Tinkers ore gen is disabled.

Using WTF's Expedition v1.2 for 1.10.2.

**Comment by WesCook** [comment]
I've created a manual fix for now using a resource pack (loaded via [Resource Loader](https://minecraft.curseforge.com/projects/resource-loader)).  These blockstates can also be used to fix the bug, if you'd like.

[resources.zip](https://github.com/WhiskyTangoFawks/Expedition/files/644562/resources.zip)

**Comment by WhiskyTangoFawks** [comment]
Actually, all you have to do is swap out the metadata in the config strings.  I've done it for newly generated configs for the next release by default.

**Comment by WesCook** [comment]
Are you sure?  I thought I'd tried that but it's possible I made a mistake.

It seemed like the blockstate files themselves had a mixup.  For instance `dense_netherrack0ore0.json` (Cobalt) has its textures set correctly under dense0, dense1, etc.  But its variant refers to dense_netherrack0ore1 (Ardite) instead.

Let me know if I've misunderstood the problem.

**Comment by WhiskyTangoFawks** [comment]
ah, then I just didn't look at it closely enough.  So, the error is just a swapped metadata value in the blockstate file, not in the config then?

**Comment by WesCook** [comment]
Yes, that's right.  You can compare from the file I attached above, but here's a screenshot showing the differences.  This is the Cobalt file (dense_netherrack0ore0).

![compare](https://cloud.githubusercontent.com/assets/792101/21148121/0a240738-c10c-11e6-8f80-012985d2c44e.png)

Left is the original, right is my fixed version.

You can see that Cobalt's translucent texture refers to the Ardite blockstate instead in the original (dense_netherrack0ore1).  So that's what needs to be swapped.
