### ISSUE TITLE
Config's aren't registering

### ISSUE THREAD

**Issue by EZEILL** [WhiskyTangoFawks/Expedition#42]
I don't know what the problem is, I tweak all of the config's to remove certain aspects of this mod but it doesn't register in game. Some of the things I do not want are blocks to fall that don't fall in vanilla, and I do not want any cracked blocks or blocks to be effected by breaking a block. Mining cracked stone makes adjacent blocks to become cobble which in turn falls, when the fallen cobble is mined if becomes an "unknown" block that I can't mine because it technically doesn't exist. It is on screen as a block but I can walk through it and it blocks me from mining any blocks through it as if it is still there. I really wan't to use this mod in my mod series but if I can't actually utilized modified configs then I can't use the mod.

**Comment by WhiskyTangoFawks** [comment]
The configs work fine when utilised correctly.  If you're changing things and it's not registering, it's user error, not a bug.

To disable the gameplay tweaks (which is what it sounds like what you want) go into the WTFCore.cfg config file, and on the gameplay tweaks config option, change true to false.  Save, a close, and that should solve your problem.

**Comment by EZEILL** [comment]
I did that and nothing happened.

**Comment by EZEILL** [comment]
Issue not resolved.
