### ISSUE TITLE
Can Expedition spawn nether materials in the overworld?

### ISSUE THREAD

**Issue by charlesbevans** [WhiskyTangoFawks/Expedition#43]
Is it possible to get Expedition to spawn nether quartz in overworld smooth stone? Can it spawn glowstone? I'm playing with using Expedition with Underworld and wanted some flavor.
I tried doing it and my changes were deleted from the config files, but I did find this:
![2016-12-17_14 31 02](https://cloud.githubusercontent.com/assets/15851438/21290436/1015f3f2-c46f-11e6-8dba-36d1c646f8a6.png)
Though, it might have been Underworld's doing.

**Comment by charlesbevans** [comment]
I got the glowstone to spawn.
`S:"# 1"=single, minecraft:glowstone@0, orePerChunk= 0 & 5, surfaces=floor&wall&ceiling, GenHeightPercentSurface= 0 & 100`
I don't want to try the nether quartz until I know it's feasible.

**Comment by WhiskyTangoFawks** [comment]
Depends on what you mean by netherr quartz.

If you just want teh vanilla block, turn off the dense ore option for it (look at the cracked stone config for how to do it), and set the background to stone, and it'll spawn.

If you want dense versions, that gets a little trickier, and you'd be better off just making quartz tone ore, rather than netherrack based quartz.

**Comment by charlesbevans** [comment]
If I can set up a wtf ore that drops nether quartz pieces, that would be great. (I'm going to look into creating an overworld quartz mod, but this is better for now.)

**Comment by WhiskyTangoFawks** [comment]
With expedition, you can make more or less whatever ore you want with the dense ore feature, as long as it's designed to drop an existing block.  So- you can very easily setup a stone background quartz ore, that drops whatever netherrquartz drops.

**Comment by charlesbevans** [comment]
I got it working, thanks. If you like, I'll write up a step-by-step of what I did with the quartz and glowstone and put it on the wiki. The extra details and pictures might help.

**Comment by WhiskyTangoFawks** [comment]
I don't have a wiki, but if you want to do a writeup, I'll happily link to it from the forum post.

**Comment by charlesbevans** [comment]
I don't have any kind of site set up. Did you want to turn on the GitHub wiki for Expeditions?

**Comment by WhiskyTangoFawks** [comment]
Post it in the minecraft forums on my thread would be the best place, that way I can just link directly to it.

**Comment by charlesbevans** [comment]
I've got something, but my Curse login is all messed up. I'll get it up as soon as it gets fixed. Thanks.
