### ISSUE TITLE
[Question] Can ores be made to spawn in non-stone blocks?

### ISSUE THREAD

**Issue by charlesbevans** [WhiskyTangoFawks/Expedition#44]
A lot of mods add decorative stone types, but it interferes with ore spawning. Will the configs accept changes to allow ores to spawn in other block types, such as diorite? I know the background can be changed, but that won't make it generate within the diorite vein.

**Comment by WhiskyTangoFawks** [comment]
If you're using the dense ore feature to generate new blocks, yes, the block already will generate.

**Comment by charlesbevans** [comment]
Got it all sorted out. Thanks!
