### ISSUE TITLE
x-mod crash with DaVinci's vessels

### ISSUE THREAD

**Issue by xenoflot** [WhiskyTangoFawks/Expedition#45]
http://pastebin.com/ym9u9e0H

Verified with only these 3 jars in the pack.

davincisvessels-1.10.2-0006-full
movingworld-1.10.2-0006-full
wtfexpedition-1.10.2_1.2
forge 2185

**Comment by yggdrasil75** [comment]
This appears to be fixed in more recent version of all listed mods. I have been using these with no error. 
I use Davincis vessels 0006
moving world 0007
wtf 1.3.6.1
forge 2185

**Comment by WhiskyTangoFawks** [comment]
Excellent, I was hoping it would fix itself when I redid the recipe scanner
