### ISSUE TITLE
possible xmod issue - mobs spawning inside walls

### ISSUE THREAD

**Issue by xenoflot** [WhiskyTangoFawks/Expedition#46]
Hi,

I have both WTF's Exped and Roguelike Dungeons in my test pack and I'm wandering around a dungeon in creative at the moment. I'm finding it's a pretty constant cacophony of "suffocating in walls" noises.

TheOneProbe shows mobs as being from wtfcore or vanilla. With this many mobs around it's hard to get an accurate assessment but it seems that the wtfcore mobs are the ones spawning with their heads inside blocks. That's observation is based on many of the wtfcore having some damage and none of the vanilla mobs being damaged.

Is this one for you or the author of Roguelike Dungeons?

Cheers!

wtfexpedition-1.10.2_1.2
roguelikedungeons-1.10.2-1.5.4
forge 2185

**Comment by WhiskyTangoFawks** [comment]
The real question isn't whose mob they are, but who's mod spawners they are.  I believe I shouldn't be redecorating roguelike dungeons.  But you should remove expedition, and try it again to see if it solves the problem.

**Comment by xenoflot** [comment]
Ah yes, the spawner makes more sense. I'll investigate some more, Cheers!
