### ISSUE TITLE
Can dense ores be made to respond to silk touch?

### ISSUE THREAD

**Issue by charlesbevans** [WhiskyTangoFawks/Expedition#47]
Is there any way to get the dense ores to respond to silk touch? It's just that some mods use the ores for various purposes including crafting and, in EU2's case, growing redstonia plants.

**Comment by WhiskyTangoFawks** [comment]
Dense ores aren't registered as ores.  Other mods won't recognise them as ores- you just want the vanilla ores, which are what the block drops.

**Comment by charlesbevans** [comment]
The dense redstone and lapis ores, for example, drop redstone and lapis respectively.

**Comment by WhiskyTangoFawks** [comment]
I suppose I could code it so that it drops the vanilla ore block, that would work.

**Comment by charlesbevans** [comment]
Rather than make everything drop a vanilla block, could you set a config option to set what drops with silk touch? I wouldn't want my overworld nether dropping netherrack-based nether quartz, and I'm going to try something cool with glowstone, but I may have to write something custom for what I want.

**Comment by WhiskyTangoFawks** [comment]
Next release version will have ores that will drop the vanilla parent ore when mined with silk touch.  I'm not doing a config, as it's kind of a pain, instead I've enabled silk touch, and then pointed it to the parent block.
