### ISSUE TITLE
Feature Request: A way to bypass the stone -> cobblestone block conversion

### ISSUE THREAD

**Issue by Kiyaku** [WhiskyTangoFawks/Expedition#48]
As discussed here: https://minecraft.curseforge.com/projects/wtfs-expedition-cavebiomes-ores-trees-and-tweaks?comment=239 

Basically a way to prevent stone turning into cobblestone blocks under certain conditions, such as:
- Pick with silk touch
- Pick of specific quality (like diamond, config option for determine quality, item or harvestlevel?)
- A new enchant that can be applied to picks (might be useful in case someone doesnt want silk touch but still want to bypass the stone -> cobble block conversion)

Cheers,
SC

**Comment by WhiskyTangoFawks** [comment]
As of 1.3beta8, silk touch should now prevent stone fracturing.
