### ISSUE TITLE
EFLN explosion from Tinkers Construct dropping original dense ore blocks

### ISSUE THREAD

**Issue by WesCook** [WhiskyTangoFawks/Expedition#49]
The EFLN is a throwable explosive from Tinkers.  In most cases it drops the correct drop, but with dense ore it drops the original "dense ore" block rather than the real ore.  This is problematic as these blocks can't be placed again (in survival, with fracturing turned on).

I reported this to boni but it looks like he's using the standard approach to block drops, by calling `dropBlockAsItemWithChance()`.  So it may be an issue on Expedition's end instead.

Bug at Tinkers repo: https://github.com/SlimeKnights/TinkersConstruct/issues/2670

**Comment by WesCook** [comment]
This may be related to the request in #47.

**Comment by WhiskyTangoFawks** [comment]
I think this might be fixed in the latest release, give it a shot and let me know.

**Comment by WesCook** [comment]
It's been semi-fixed.  Regular explosions now drop only one of the ore drops, regardless of density.  This may be intentional.

EFLN explosions however drop the correct density of the ore, plus one extra.  So a full dense iron ore drops 4 pieces total, which is probably not desired.
