### ISSUE TITLE
Disabling "Remove Vanilla Tools Recipes" Crash

### ISSUE THREAD

**Issue by WenXin20** [WhiskyTangoFawks/Expedition#5]
Setting this config option to false with tinkers crashes the game.
[Crash Report](http://pastebin.com/j3nwHPjH)

**Comment by WhiskyTangoFawks** [comment]
Thanks for catching this, simple fix.

Beta 11.1 just went out to curseforge, should be live in the next 10-20 minutes.

**Comment by WenXin20** [comment]
Thanks

**Comment by WenXin20** [comment]
I just tested it, and 7t still crashes, even with that option set to true, I even deleted the config with the same result. It crashed right before it finished loading the game on forge 2076

**Comment by WhiskyTangoFawks** [comment]
Well, I fixed the first issue, and ran a quick test with it on and off in my modpack with it on and off, so I'm going to need the crash log to see what it's doing now.  Post it, and I'll have a look at it later tonight.

**Comment by WhiskyTangoFawks** [comment]
I've uploaded a new beta, that if this crash occurs, will tell me what item is the source of it, and should help me track down why.

**Comment by WenXin20** [comment]
It looks like something to do with Extra Utils or Malisis Doors?: 
[Log](http://pastebin.com/tczRzTib)
[Crash Report](http://pastebin.com/Wiqgkj0Q)

**Comment by WhiskyTangoFawks** [comment]
This is really strange.

It's passing a != null check, but then causing a null pointer crash, which should be impossible.

I've just uploaded beta11.3, which should suppress the crash at least, and print out what item is causing it.  

You can ignore the stuff about unsupported recipe types- that's actually my mod saying it's ignoring those recipes, and not trying to do anything with them.

**Comment by WenXin20** [comment]
[Crash Log Again](http://pastebin.com/7wUgg82C)

**Comment by WhiskyTangoFawks** [comment]
Try beta 11.4

**Comment by WenXin20** [comment]
OK , that worked. Here is a log if you need it.
http://pastebin.com/K6uXcdSk

**Comment by WhiskyTangoFawks** [comment]
What mod is slate smooth pillar, and smooth wedge from?  Cause that's what was causing the crash.  Additionally, in your modpack there's a TON of recipe types that my parser can't deal with, if you're not interested in using the recipe crafting table I added in my last update, I recommend disabling it, as all the recipe types it skips won't show up (because I can't access the recipe class to get the ingrediant list, because the mod author is using a custom one, instead of the standard forge ones).

**Comment by WenXin20** [comment]
The wedges and pillars are from the missing pieces mod, and thanks for the suggestion. Thanks for the help
