### ISSUE TITLE
Project-E Morningstar Collects wtfores and fractured stone

### ISSUE THREAD

**Issue by charlesbevans** [WhiskyTangoFawks/Expedition#50]
Like it said. I had the most recent Expedition and Project-E, and started mass mining with the charged up right-click function of the red matter morningstar (which is a bit buggy still). My inventory filled with various Expedition generated items (dense ores, fractured stone).
I was able to place the ores back down and mine them normally (they turn to maximum density when you place them), but I thought this might be a behavior that needs catching.

**Comment by WhiskyTangoFawks** [comment]
Alright, I think I've fixed this.  Let me know if it's still bugged in the latest release.
