### ISSUE TITLE
Missing json Files

### ISSUE THREAD

**Issue by WenXin20** [WhiskyTangoFawks/Expedition#51]
Forge 2185
Expedition v1.3
After installing and starting a world, I noticed that most blocks are missing their json files, dirt, dense ores, stalagtites, stalagmites, stones, and the underground Biomes stones. I just see a purple and black pattern on the blocks.
The underground Biomes sand, at least from the creative menu, all place as the silt stone sand.

**Comment by charlesbevans** [comment]
I came to mention the missing textures too.
@WenXin20 today's release was a beta. My custom stuff is working still, so it's just the resources. Until WTF can add the missing files, you can roll back to the release version for full textures.

**Comment by WhiskyTangoFawks** [comment]
As per the release notes on both the curse file, and on the MCF, that's behaviour as intended.  The blockstate jsons now auto generate and are placed into a resource pack (that also alto generates),  You just have to enable it.

The next release should have the resource pack enable itself, I've just not figured that out yet.

**Comment by WenXin20** [comment]
Ok, I see, Thanks

**Comment by charlesbevans** [comment]
The version of the release notes you're talking about is only visible from the Curse file detail page for that release. It doesn't show up in the regular change logs on the Curse client or in the Curse web page. It looks very exciting though, I'm really enjoying using this as a major part of the pack I'm working on.
