### ISSUE TITLE
Gen World Crash w/ Underground Biomes Construct

### ISSUE THREAD

**Issue by WenXin20** [WhiskyTangoFawks/Expedition#52]
Forge 2185
Expedition v1.3
Underground BC v0.9 Beta 11
I get a crash while generating the world with both these mods together,
[Crash Log](http://pastebin.com/P7en3zrc)

**Comment by darkphan** [comment]
This happens even without Underground Biomes Construct

**Comment by ate0ate** [comment]
Yup, same crash here without UBC.

**Comment by WhiskyTangoFawks** [comment]
Should be sorted in the latest release
