### ISSUE TITLE
No Class Def Found Error Crash

### ISSUE THREAD

**Issue by WenXin20** [WhiskyTangoFawks/Expedition#53]
Forge 2185
Expedition Mod v1.3 Beta 3
It crashed on game launch, with something to do with the configs.
[Crash Log](http://pastebin.com/LumXGvSe)

**Comment by WhiskyTangoFawks** [comment]
Update RTG and UBC, see if that fixes it.

**Comment by WhiskyTangoFawks** [comment]
And forge- make sure you're on the latest 1.10.2

**Comment by WenXin20** [comment]
I used the latest of forge and UBC, but I didn't have RTG installed.
Forge 2185
UBC v0.9 Beta 11

**Comment by WenXin20** [comment]
I tried adding RTG 4.1.2.0 and get the same crash still.

**Comment by WenXin20** [comment]
I also have Jei, Optifine, and Better FPS installed.

**Comment by RiverC** [comment]
I had this same error. Downgrading from 1.3 Beta 3 to 1.3 Beta 2 gave me the same error, but 1.3 Beta 2 to 1.3 removed the problem. I suspect a change from 1.3 to Beta 2 is the culprit. (I don't know what kind of scala stuff you're doing, so I can't comment!)

**Comment by WhiskyTangoFawks** [comment]
I had an incorrect import from a scala library in beta 3.  Beta 4 went out last night- and at least in my testing fixed the crash.

**Comment by WenXin20** [comment]
It works for me now. :)
