### ISSUE TITLE
Significant performance decrease in latest builds

### ISSUE THREAD

**Issue by WesCook** [WhiskyTangoFawks/Expedition#54]
Since The 1.3 builds, there has been a significant drop in performance during world generation.  New worlds take easily 10x longer to generate, and any exploration leads to immediate TPS drops.

Let me know if you're unable to reproduce, and I can help set up a test case.  But right now it's bad enough that I've needed to revert to v1.2.

**Comment by WhiskyTangoFawks** [comment]
Yeah, there's a good reason it's marked as beta.  I hadn't noticed the drop, but I'll look into it.  Is this alone, or with other mods?

**Comment by WesCook** [comment]
It's with other mods, a mid-sized pack.  I can generate a modlist if that'd be helpful, or do some isolated testing instead.

**Comment by WhiskyTangoFawks** [comment]
Are you running Ruins or UBC?

**Comment by WesCook** [comment]
Yes to UBC, no to Ruins.

I'm actually the guy that uploaded the UBC blockstate files to the Minecraft Forums.  I've been playing with the mod a lot lately, trying to get it integrating nicely with my pack.  For this test though I used default configs of both versions of Expedition, and removed any customized Resource Packs via ResourceLoader.

**Comment by WhiskyTangoFawks** [comment]
Couple things to test  then- the only significant change to world generation in 1.3 is the inclusion of the UBC blocks.  Did you notice any generation slow down on 1.2 when you manually added the UBC blocks?  Does it go away if you run it without UBC? (If that's the case- it indicates the hashsets I'm using aren't distinct enough with the added blocks).  The other thing to try, is disabling the resourcepack that the blockstate files generate into in 1.3 (if that's the case, then it's a memory issue, and I need to finish the option for single-model blockstates).

**Comment by WesCook** [comment]
I'll run some tests and get back to you.  I'll use initial world generation time as a metric, as it seems to be more reliable than testing TPS while moving.

**Comment by WhiskyTangoFawks** [comment]
additionally beta5 just hit curseforge, which finishes the cleanup of the config files, and fixes a few bugs with UBC stone integration.

**Comment by WesCook** [comment]
I'm getting an NPE from beta 5.

http://pastebin.com/T232bqka

**Comment by WhiskyTangoFawks** [comment]
yeah, bug where it would try to load UBC stuff without checking if UBC was installed first.  Uploading a new version now.

**Comment by WesCook** [comment]
I've completed the benchmarks.

**v1.2**

| UBC           | Loaded Resources | Time       |
| :-----------: | :--------------: | :--------: |
| Yes           | No [1]           | 48 seconds |
| Yes           | Yes [2]          | 54 seconds |
| No            | No               | 48 seconds |
| No            | Yes [2]          | 46 seconds |

**v1.3b6**

| UBC           | Loaded Resources | Time                  |
| :-----------: |:---------------: | :-------------------: |
| Yes           | No [3]           | 4 minutes, 26 seconds |
| Yes           | Yes [3]          | 4 minutes, 26 seconds |
| No            | No               | 4 minutes, 37 seconds |
| No            | Yes              | 4 minutes, 45 seconds |

Methodology:

I measured the time of starting a new world by watching the log, and calculating the difference in timestamp from `Starting integrated minecraft server version 1.10.2`, to `Server side modded connection established`.  This didn't measure starting the Minecraft client, only creating a new world.

I re-created the same seed to try and reduce randomness, but it's still not extremely scientific.  Due to the number of tests I also did only one pass per test.  However, it shows a pretty consistent difference between the two versions in all configurations.

[1] Disabled pairing in wtfcore
[2] Installed via ResourceLoader
[3] Installed via generated resource pack

**Comment by WhiskyTangoFawks** [comment]
Wow, that's thorough.

Something weird is definitely happening.  I've not touched world generation in this update- it's strictly been config based stuff.  So I need to figure out how that's having a knock on effect...

Thanks for this.  I'll be traveling, so I might not get to this for a few days, but it's my first priority.

**Comment by WhiskyTangoFawks** [comment]
Also, given you used the old one pretty extensively, any thoughts on the new config file setup?

**Comment by WesCook** [comment]
I haven't had a chance to really test out the new system yet, so I'll need to get back to you on that.

My initial impression (just at a glance) is that the method for generating configs is a whole lot more user-friendly now.  Editing values in a single line was tough, especially with 24 stone variants making a mess of it.  It's also a lot more consistent now, without the split of "vanilla ore", "tinkers ore", and "custom ore" sections.  I like that a lot.

I'm going to need to reimplement my custom ores, so I can give a better answer then.

I'm not super thrilled by the current method for adding Resources to UBC ores though.  I found using ResourceLoader made the process more seamless, as it wasn't exposed to players that these custom assets are being loaded.

Obviously you don't want players/pack authors to have to include a mod like ResourceLoader to play your mod, but the current solution doesn't seem ideal either.

I wonder if it's possible to tap into the Forge model registry and add those texture from code, rather than leaning on the vanilla Resource Pack system.  It'd reduce file IO to help performance, and not expose players to it as well.  A number of the guys in the Forge IRC are knowledgeable on this stuff.

But I'm going to need to play with these changes some more before I can really give a useful comment.  The performance issue has made testing changes a lot slower, so I wanted to address it first before diving in too deep.  I'm sure I'll have more for you later.

**Comment by WhiskyTangoFawks** [comment]
thanks.  When you do get around to generating the ore stuff let me know how it goes, and if there's any other features that would make life easier.  Two things with the UBC compatability- make sure you're regenerating the configs so that the UBC stones get added to the defaults, and be aware that "igneous", "metamorphic", and "sedimentary" all are accepted instead of a block registry name and meta, and it'll add all 8 variants for that subtype.

**Comment by filki7** [comment]
im have server updating issues with this modpack missing resource files from 1.2 to 1.3

**Comment by WesCook** [comment]
Have you enabled the Resource Pack that is generated using the betas?

**Comment by filki7** [comment]
i just downloading all the mods expert server and copied and pasted didnt change any config files

**Comment by filki7** [comment]
i updated from all the mods 1.10 to 1.11 and had purple blocks where soul dirt is and in the under ground caves

**Comment by WesCook** [comment]
They really shouldn't be using the betas yet, but if they're using 1.3 you'll need to enable the resource pack as explained on the Curseforge page.

In the future though, please consider creating a new Issue or use the mod comments page to ask questions.  Alternatively, when it concerns a modpack you should talk to the modpack authors first.  They likely know more about their specific use case.

**Comment by WhiskyTangoFawks** [comment]
You've downloaded a beta version of WTF-Expedition, I recommend going back and downloading version 1.2 until 1.3 is uploaded as a release version.

But yes, fixing the null texture blocks is done by enabling the resource pack that the mod now ships with.

**Comment by filki7** [comment]
thank you guys

**Comment by WhiskyTangoFawks** [comment]
In regards to the world generation lag, I've isolated it the Ores module, which makes sense as that is the thing most likely to be effected by the config changes.  Still trying to figure out the why...

**Comment by WesCook** [comment]
Is your Github up to date?  I'm rusty with Java, but I can download a copy and see if I can help profile the performance.

**Comment by WhiskyTangoFawks** [comment]
It is now.

**Comment by WesCook** [comment]
It looks like `WTFStoneRegistry.cfg` isn't being generated on fresh configs anymore, and this is leading to a crash in beta 6.  Possibly `WTFOresConfigV2.cfg` as well.

Explains why my local version wasn't compiling...

**Comment by WesCook** [comment]
Had a few troubles getting things compiling.

I had to regenerate the gradle files as it seemed to be missing some tasks.  The [build.gradle](https://github.com/WhiskyTangoFawks/Expedition/blob/master/1-9Forge/build.gradle) in the repo also looks like a default file, with an example modid and such.  No biggie, but just an FYI.

I also saw an error locally where I need to generate the config for `WTFStoneRegistry.cfg` first, otherwise I got a crash.  Doesn't seem to be the case with the beta 6 jar though.  I copied over the configs and that seemed to do the trick.

I'm just playing around with some profiling now.  It seems to run significantly faster by itself than in a larger pack, so just adding some `System.currentTimeMillis()`'s in code doesn't show any immediate problems (that I can see).  It might be more helpful to throw into a larger pack to test, and compare against the previous version.

Not sure I can export the mod without an updated build.gradle file though - unless I'm missing something.  That's where I'm at now.

**Comment by WhiskyTangoFawks** [comment]
I've done a bit of profiling, definitely in the ore module, as if I disable that there's a big performance increase.  Profiled the individual ore generators, and the cave and underwater ones are having occasional huge spikes, particularly the underwater.  You might try disabling the ore gen routines using those, and see if you get much of a difference.

I found the bug with the config, working on it now.

**Comment by WhiskyTangoFawks** [comment]
New version's up on github, should solve the crash issue.

I've never touched the defaults in build.gradle, just rename the file.  If it's not obvious, I'm not a trained coder, just picked up all of this by messing around a lot and watching tutorials.

There are definitely performance issues with the secondary gen routines (cave, and underwater).  Fixing them means optimising how it's interfacing with the world scanner, and probably making some changes to the scanner itself to streamline water detection.

**Comment by WesCook** [comment]
Glad to hear you're making some headway.

No worries on lack of programming experience.  I'm completely self-taught as well; though I've been doing it for about 10 years now.  Java and Minecraft dev however are still pretty new to me.  I actually just released my first mod [last week](https://github.com/WesCook/WateringCans), so starting to get a feel for it.

If you're interested, I could offer some help on the boring stuff like gradle setup.  A lot of it is personal preference but there are some best practices.  Having gradle talking to your IDE is nice because it helps automate some of the repetitive tasks, like updating Forge, or generating builds.

I also restructured [my fork of Expedition](https://github.com/WesCook/Expedition) while trying to get it to compile, just to clean things up a bit.  But then I'm pretty anal about these things.

**Comment by WhiskyTangoFawks** [comment]
Latest build has teh performance increases for the underwater generation routine, which was the major source of the problem.  I'm still not sure why it only became apparent with the latest update- it should have been a problem prior to that.

**Comment by WesCook** [comment]
Just to confirm the improvement, I recorded 53 seconds to generate a new world in the same pack as before.  Thanks for putting in the time to work to resolve that!

**Comment by WhiskyTangoFawks** [comment]
Hmmm, still slower than I'd like, but at least back within an acceptable range.
