### ISSUE TITLE
Stone not changing to cobble during the breaking process

### ISSUE THREAD

**Issue by darkphan** [WhiskyTangoFawks/Expedition#56]
One of the recent updates changed the behavior when you break stone, it no longer changes to cobble, it just drops cobble.

**Comment by WhiskyTangoFawks** [comment]
Try deleting your stone registry config. If that doesn't work, check the
entry for vanilla stone and make sure it's got a cobblestone in it.

**Comment by darkphan** [comment]
I have deleted the stone registry config and it still does not work. Breaking stone just drops cobble like vanilla minecraft would instead of changing the block to cobble then having you break that. This is with a new instance with only WTF expedition in it as well to validate that other mods are not causing any interference

**Comment by WhiskyTangoFawks** [comment]
I've found the problem and fixed it.  Next release will have the issue sorted.
