### ISSUE TITLE
[suggestion] Automatic texture generation 

### ISSUE THREAD

**Issue by ruyanve** [WhiskyTangoFawks/Expedition#59]
Hey hey,

I've been using your cave decoration mod since forever and now that I am setting up a new server I wanted to use your ore generation as well. Working on setting up the config and textures I need I was thinking... This isn't really user friendly and there MUST be a way to speed up the process.
Have you ever looked into the dense ore code for texture generation? Maybe have a talk with RWTema about how to adapt his method to your mod?
I don't know poop about java, so I have no idea if this is even feasible, but maybe something could be done to make that portion of your mod more accessible and user friendly.

Here's the link to dense ores automatic texture generation: https://github.com/rwtema/DenseOres/blob/master/src/main/java/com/rwtema/denseores/client/TextureOre.java

Cheers man, I'll be nagging you about tons of stuff in the next weeks, so you better get used to it! :-D Kidding, I love your mod and hope I maybe can help in any way to get it to where it belongs (the top of curses popularity list)! :-)

**Comment by WhiskyTangoFawks** [comment]
If you've looked at the latest beta, you'll notice that it's a LOT more user friendly than it used to be.  The bottom like is that because it's not just dense ores, but dense ores combined with an entirely new generation style, doing new custom stuff automatically isn't going to work, because I don't know how the user is going to want ore generation handled from other mods (how much, where, etc).

**Comment by ruyanve** [comment]
I know it's not easy (impossible) to generate mod ores automatically... That's not what I was asking for.

I was asking for a simpler way to have the textures set automatically which is what RWTema is doing and the link I posted is all about.

I understand the way this works, even tho I know nothing about Java, I've been around that stuff for such a long time, I know my way around. But to manually set up textures for all the ores in dense states is a pita! And since RWTema has a way to do it automatically, I was wondering if his method could be adapted to your mod.

Thanks :-)

**Comment by WhiskyTangoFawks** [comment]
The last update I did does generate the blockstates automatically.  You do need to give it a few bits of information, but it's no longer completely manual.

**Comment by ruyanve** [comment]
oops, didn't realize I was still using the resource pack from the version before I edited all the ores in... doh!
Well, the blockstate configs are a little cryptic, but I'll work my way thru :-P cheers mate, and again, don't get me wrong... I don't mind working on configs to get things rolling, I was thinking about the "regular" user and what could be done to get this mod where it belongs, which is the top of curses popularity list!

**Comment by WhiskyTangoFawks** [comment]
Glad you're enjoying it.

Yeah, the blockstates is the main thing that's cryptic- hence why I've set it up to generate them all automatically.  Just enable the WTFOres pack, and any custom ores you setup will have their blockstate files written to the WTFOres resource pack automatically

**Comment by ruyanve** [comment]
I got it working, but I had to realize that while the blockstates are automatically generated, the textures are not. Or did I miss something?
That sadly means I need to use Dense Ores anyway and disable the dense option from you, since I won't be able to modify all the different resource packs from all the guys on my server. Damn! :-D

**Comment by WhiskyTangoFawks** [comment]
The textures need to be manually generated but it is an overlay based system, so all you need is the ore, with a transparent background, and the stone texture is pulled from whatever pack you have installed (or gravel, or sand, or whatever the background is set to).  Once you know what you're doing, you can do it in a couple minutes with paint.net.  I had a look at the link you sent regarding dense ores, it's an interesting idea, but I'd expect it to be prone to screw up with less simple texture packs.

**Comment by ruyanve** [comment]
Oh I know, I'm the guy who started the Sphax modded texture project (I also did the official Forestry Banner :-P) back when the whole thing got rolling.
I'll be testing various texture packs with Temas Dense Ores today and will report back later if you want to. Like I said, I am thinking of accessibility here, because most people won't be able to edit the needed textures and I can only imagine how often people will ask about this over and over again!

**Comment by WhiskyTangoFawks** [comment]
You're not wrong.

If you do update any packs, let me know and I can host them, (or just link to them if you want).

**Comment by ruyanve** [comment]
Ok, so after a lot of testing... RWTemas Dense Ores works ok with vanilla, but the higher in resolution I go with textures, the worse it gets. Since that's not really an option, I started working on some overlays for your version... Since it's the most simple one, I started with Sphax: https://drive.google.com/open?id=0BypYxBlEdgyibFVWbGJfQ29yVmM
These should cover IC2, TiC, Immersive Engineering and Vanilla. I know sphax is a little picky about where to download his assets so maybe hold of linking them for now, I'll have a talk with him.
I was wondering about location and any naming conventions I should know about before continuing with other well knows packs to make this compatible across the board.

**Comment by WhiskyTangoFawks** [comment]
In terms of naming conventions, it's more or less customisable, because part of the ore config is an option to redirect the texture name.  By default, it bases it off the registry for new ones.

Just FYI, the one texture pack I'm working on is for Conquest, covering my mod and UBC.

**Comment by WhiskyTangoFawks** [comment]
The other thing you probably want to be aware of, is the fancy blockstate option in the latest beta.  Allows you to switch between semi-transparent rendering with a multi-model, and simple non-transparent cutout overlays.  The fancy option also has the texture rotation options.

**Comment by ruyanve** [comment]
Nice, I'll get on Pixel Perfection and Lithos next. Will do my own Vayukan mix as well and have a look at Faithful. We should be set then ;-)

**Comment by ruyanve** [comment]
Here's the mod overlays vanilla style: https://drive.google.com/open?id=0BypYxBlEdgyiWkxGbDU1aEVSTFk
Started working on Pixel Perfection.
