### ISSUE TITLE
Strange Duplicate Mod issue

### ISSUE THREAD

**Issue by darkphan** [WhiskyTangoFawks/Expedition#62]
Appears that Expedition is using "examplemod" as the modname in the code, when trying out another mod for my modpack I get a duplicate mod error:

Duplicate Mods:
        examplemod : /home/mc/wgda/mods/Crocoducks-1.1.jar
        examplemod : /home/mc/wgda/mods/WTF-Expedition_1.10.2_v1.3Beta7.jar

I have reported this to Crocoducks as well

**Comment by WhiskyTangoFawks** [comment]
Quite possibly, I've had to re-update my dev environment a couple times.  I'll get it sorted in the next release.
