### ISSUE TITLE
Some mod block textures don't work for the Lava Crust & Mossy Stones

### ISSUE THREAD

**Issue by WenXin20** [WhiskyTangoFawks/Expedition#63]
Expedition v1.3  Beta 7
Forge 2185
Chisel 0.0.7.7
Environmental Tech 0.10.5h
I noticed that with some mods, the decoanim textures and the decostatic textures don't generate properly. 
For example, the Chisel basalt blockstate that is generated shows as **chisel:basaltextra**, but should generate as **ctm:chisel:basalt/extra/raw** in the default.json file, which is found under the path **assets\chisel\blockstates**.
For the Environmental Tech Alabaster blockstates, the **environmentaltech:alabaster** also show up as the purple and black glitched texture, but I can't figure out the correct blockstate path.

My blocks in the Master List in the Stone Registry:
        

- chisel:basaltextra@7
- chisel:limestoneextra@7
- chisel:marbleextra@7
- environmentaltech:alabaster@0
- environmentaltech:hardened_stone@0

**Comment by WhiskyTangoFawks** [comment]
If a mod doesn't follow the exact same naming convention as vanilla, then the assumptions that I make about what the mods textures and blockstate locations are are false.  When adding stuff to the stone registry, you need to make sure that the texture locations and blockstate locations that it guesses are right.  I'm not currently able to retrieve that information from the game, it needs to be put in manually.

**Comment by WenXin20** [comment]
Ok, I also noticed that the environmental tech mod seems to call it's textures normally, but it has several block textures in one json file, and it doesn't seem to work to put one of those from within the file.
