### ISSUE TITLE
Resourcepack does not generate properly on linux

### ISSUE THREAD

**Issue by portablejim** [WhiskyTangoFawks/Expedition#64]
Since linux uses '/' instead of '\' for the separator between folders and files.

WTF-Expedition_1.10.2_v1.3_Beta6.jar

After loading, there is a bunch of files created in the minecraft folder (1 file per line).

```
resourcepacks\WTFOres
resourcepacks\WTFOres\assets
resourcepacks\WTFOres\assets\wtfcore
resourcepacks\WTFOres\assets\wtfcore\blockstates
resourcepacks\WTFOres\assets\wtfcore\blockstates\dirt0DecoStatic.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\gravel0DecoStatic.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\netherrack0DecoAnim.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\netherrack0DecoStatic.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\netherrack0SpeleothemFrozen.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\netherrack0Speleothem.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\obsidian0DecoAnim.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\obsidian0DecoStatic.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\obsidian0SpeleothemFrozen.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\obsidian0Speleothem.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\red_sandstone0DecoAnim.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\red_sandstone0DecoStatic.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\red_sandstone0SpeleothemFrozen.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\red_sandstone0Speleothem.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\sand0DecoStatic.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\sand1DecoStatic.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\sandstone0DecoAnim.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\sandstone0DecoStatic.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\sandstone0SpeleothemFrozen.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\sandstone0Speleothem.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\stone0DecoAnim.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\stone0DecoStatic.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\stone0SpeleothemFrozen.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\stone0Speleothem.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\stone1DecoAnim.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\stone1DecoStatic.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\stone1SpeleothemFrozen.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\stone1Speleothem.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\stone3DecoAnim.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\stone3DecoStatic.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\stone3SpeleothemFrozen.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\stone3Speleothem.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\stone5DecoAnim.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\stone5DecoStatic.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\stone5SpeleothemFrozen.json
resourcepacks\WTFOres\assets\wtfcore\blockstates\stone5Speleothem.json
```

Note that these are not in folders but the files have the backslashes in their names.

![screenshot at 2016-12-30 15-32-41](https://cloud.githubusercontent.com/assets/339225/21559718/5adba6c6-cea5-11e6-8cc6-11e79910867c.png)

**Comment by WhiskyTangoFawks** [comment]
I can see how that would be a problem.

I'll see what I can do about swapping it over to a default character.

**Comment by portablejim** [comment]
http://docs.oracle.com/javase/1.5.0/docs/api/java/io/File.html#separator might help.

**Comment by WhiskyTangoFawks** [comment]
It does help.

New beta just went up to curseforge, needs to be approved but will then be available.  Let me know if it solves the issue or not.

**Comment by portablejim** [comment]
Folders are correct, files still incorrect.

In other words "resourcepacks/WTFOres/assets/wtfcore/blockstates" exists but is empty, the files are still in the main minecraft folder with backslashes.

**Comment by Dragnier** [comment]
I have this on the Mac. Causes lots of purple/black checkers in-game.

**Comment by WhiskyTangoFawks** [comment]
Next beta release should have this issue sorted.  I found what would cause that.  Unfortunately I can't test it myself.

**Comment by Dragnier** [comment]
That's why I like to play mods like this and help with the debug. I'm in University for game design and I know how hard it is to do this stuff without feedback.

**Comment by DeadSix27** [comment]
In which version is this fixed? 
[R] WTF-Expedition_1.10.2_1.3_Beta8.jar [released 2 days ago at point of writing]
or 
[B] WTF-Expedition_1.10.2_v1.3.jar [released a few hours ago at point of writing]

**Comment by WhiskyTangoFawks** [comment]
Release 1.3 went live yesterday, and should have it fixed.  Let me know if it doesn't.

**Comment by DeadSix27** [comment]
@WhiskyTangoFawks actually deleted my post as i realized i could have just tested it.. and i did, works fine.
(But ye, as reference, i did ask whether this issue was fixed in the (at time of writing, newest version))
and it seems like it is.
