### ISSUE TITLE
Block registration conflict when two ores share same name/metadata (eg. Tinkers & Immersive Engineering)

### ISSUE THREAD

**Issue by WesCook** [WhiskyTangoFawks/Expedition#67]
Previously there was an option to add dense Tinkers ores to the nether.  That appears to be removed in the new Ores configuration.  However, setting `tconstruct:ore@0 #vein` leads to a crash.  It appears to be registering, but not actually appearing in game.

```
Caught exception from Wtfs Expedition (wtfcore)
Caused by: java.lang.IllegalArgumentException: The name wtfcore:dense_stone0ore0 has been registered twice, for Block{wtfcore:dense_stone0ore0} and Block{null}.
```

Using 1.10.2-1.3.1.

**Comment by WhiskyTangoFawks** [comment]
Yeah, I've not added them as defaults currently.  It's on the todo list.

I'm not entirely sure how you've managed to do that.  Check your config, make sure that there aren't any extra lines or commas where there shouldn't be (I think maybe it's trying to loop through another time and generate a block, but it's a blank line, hence the null).

**Comment by WesCook** [comment]
I thought it might be something like that, but all spacing/commas are consistent.

I've done a bit more testing and found a reproducible test case.

```
"1 master ore list" {
    S:"Master list of all ores generated, add ore blocks to this list, then run minecraft, in order to generate their config options" <
        immersiveengineering:ore@0 #vein
        tconstruct:ore@0 #vein
     >
}
```
So IE Copper + TConstruct Cobalt together create this error.  I did some further testing, and it actually comes down to the metadata matching.

`immersiveengineering:ore@0` and `tconstruct:ore@0` creates an error.
`immersiveengineering:ore@1` and `tconstruct:ore@1` creates an error.
`immersiveengineering:ore@0` and `tconstruct:ore@1` **does not** create an error.

So that's interesting.  I've attached two crashlogs.  One using @0 for both values, and one using @1 for both values.

http://pastebin.com/AqK0Qah9
http://pastebin.com/CwkFeQu3

You can see the duplicate registered block (wtfcore:dense_stone0ore0) changes.

Unfortunately I believe this exposes a flaw in your approach for registering dense ore.  It only uses the block name and metadata to determine the new name, but not the mod ID.  Because both mods use the same block name and metadata, it creates a conflict when both are registered at once.

I didn't notice this in the old version because the TConstruct ores were registered automatically.

I don't see an easy fix other than updating the block registration names to also use the modid.  That would unfortunately break existing worlds, and require custom blockstates be updated.

**Comment by WesCook** [comment]
I do have a suggestion.  This would be another large update to your config system, but would address this problem and perhaps make things easier to manage.

What if you allowed pack authors to set friendly names for mods in the ores config file?  So instead of referring to copper as immersiveengineering:ore@0, it would just be "copper" everywhere.

So the blockstate becomes `dense_copper_stone0`, the lang string is `tile.dense_copper_stone0.name`, the ore configurations become `"config for copper #vein"`.  It would make the configs/blockstates easier to manage, and resolve the problem of ores from different mods having conflicting names.

Plus less of this:

![blockstates](https://cloud.githubusercontent.com/assets/792101/21658311/edd5bc40-d27a-11e6-8ff4-531a1e1f5620.png)

Thoughts?

**Comment by WhiskyTangoFawks** [comment]
From my perspective, the flaw is that mod makers have named their block "ore", rather than something a bit more descriptive.  But that doesn't help fix it.  So.

The simple solution is likely just to add an override option for the registry name, which is more or less what you're talking about.  Allow the user to rename the block to whatever they want, and at that point if the user breaks their own world that's their own problem.  And even that's not that simple, given I need to make sure that the change populates through the blockstate writer.

The alternative is to grab another mod that adds the same ores, and registers them to the ore dictionary (e.g. metallurgy style).

I'll leave the issue open, and get around to adding a registry name override option eventually, but I need a break from coding configs, so it might be a while before I get to fixing it.

**Comment by WesCook** [comment]
I'll update the issue name to be more descriptive.

I could use [B.A.S.E](https://minecraft.curseforge.com/projects/b-a-s-e) to add the other ores, though I think I'll just use non-dense ores for Tinkers for now.  Nobody likes mining in the nether anyway.

**Comment by WhiskyTangoFawks** [comment]
I've added a block reg name override that will ship with the next release.  In my limited testing, it seems to work fine.

**Comment by WesCook** [comment]
Cool, thanks.  I'll check it out when it goes up.

**Comment by WhiskyTangoFawks** [comment]
Looking back at the code, for some reason it checks for contains "igneous" rather than = "igneous",  I think maybe I was having issues getting it to recognise it.  So on the current version, you can't do a single UBC stone type.  I should be able to fix that though.

**Comment by WesCook** [comment]
Random guess, but did you do `==` or `.equals()` for the string comparison?  You need to do the latter in Java for silly reasons.
