### ISSUE TITLE
Unable to disable mining speed modifications

### ISSUE THREAD

**Issue by Jdavidlol** [WhiskyTangoFawks/Expedition#68]
Currently unable to disable mining speed modifications.

**Comment by WesCook** [comment]
Does setting it to 100 in the stone registry not work?  I found this worked for me.

**Comment by Jdavidlol** [comment]
I don't know if I am doing something wrong, but from what I can tell setting each individual ore to 100% in the stone registry config does not change anything on 1.3.1 for 1.10.2 MC. I have tried older versions down to 1.1 but they cause crashes on the client side. Im gonna try to see if I can get the stone registry work around to work again.. maybe I made a mistake.

**Comment by WhiskyTangoFawks** [comment]
If the stone registry isn't working, that is a problem I need to fix.  But if you don't feel like testing it, the new version has a config option in the gameplay config to just disable the listener for stone mining speed completely, which should work.

**Comment by WesCook** [comment]
I was able to modify the stone mining speed with success in the previous release, so the issue may be elsewhere.  Though I was testing with Tinkers tools if that could be a factor (vanilla tools were disabled).
