### ISSUE TITLE
Skelton Mages spawning in floors

### ISSUE THREAD

**Issue by ruyanve** [WhiskyTangoFawks/Expedition#69]
I have noticed a large number of skeleton spawns end up in walls and floors and suffocate, is it possible that your mod has anything to do with it?

**Comment by WhiskyTangoFawks** [comment]
Given that my mod is the only one that adds skeleton mages to the world, probably.  I'll look into it.

**Comment by WhiskyTangoFawks** [comment]
Finally got around to rewriting my dungeon generation code.  This issue should no longer occur.

**Comment by ruyanve** [comment]
Cheers mate, updated our server a minute ago, will report back if I spot something.
