### ISSUE TITLE
Expedition only includes cavebiomes config

### ISSUE THREAD

**Issue by alphaJackal** [WhiskyTangoFawks/Expedition#70]
I downloaded WTF's Expedition via the curse platform, which in turn gave me wtfcavebiomes-1.7.10_V1.6.jar, and launching with that only gave me a config file for cavebiomes. Trying to use the WTF-Expedition_1.10.2_V1.3.3.jar i found online results in the mod not doing anything at all, or even being recognized as existing by minecraft. Looking at the config file I did manage to generate, no options not related to cave biomes were present at all.

**Comment by WhiskyTangoFawks** [comment]
You somehow managed to download the wrong file.  The file labelled 1.7.10 is the 1.7.10 version.  You need to download the correct file.
