### ISSUE TITLE
tile.stone0DecoStatic.2.name causing lan server to hang or crashes

### ISSUE THREAD

**Issue by bootstrap22** [WhiskyTangoFawks/Expedition#71]
Sometimes when the cracked stone blocks are mined, the server either hangs or crashes. I've used a profiler to narrow down the hangs to a chunk a player was mining in each time, and over several occurrences we've determined it always happens after a cracked stone block has been mined. Crashes are the same, just after the cracked block was mined.
These are, I believe, the key lines from the crash log: 
PM Description: Watching Server java.lang.Error
	at java.util.ArrayList.remove(Unknown Source)
	at net.minecraft.util.ClassInheritanceMultiMap.remove(SourceFile:83)
	at net.minecraft.world.chunk.Chunk.func_76608_a(Chunk.java:750)
	at net.minecraft.world.chunk.Chunk.func_76622_b(Chunk.java:735)
	at net.minecraft.world.World.func_72939_s(World.java:1777)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

I'm aware the error doesn't mention the mod but this is the 17th time now, and the 12th time that we're sure it's occurred immediately after breaking said block. 

I have the gameplay tweaks section of the mod disabled as the cracking seemed to be lagging the server. I assumed that info is important

This is my first error report on github so apologies if I didn't report it correctly, as thanks very much.

**Comment by WhiskyTangoFawks** [comment]
Thanks for the report, I'll go ahead and look into it.  Let me know if you figure out any other information on how to reproduce it.

**Comment by bootstrap22** [comment]
Will do. I've tried attaching all the error files generated so far, and hopefully that's worked. It doesn't seem to happen when just breaking the blocks in creative, nor with tnt (also in creative).
The crash itself has only happened so far with the server, when testing in client I've only had it hang, which unfortunately produces no logs (that I know of). Server has had more testing however.
Sometimes it happens immediately after reboot busting one to test, other times I hasn't crashed, I've gone on mining out an underground base, breaking plenty of them before it happens.
Considering how often this is happening, and that no one else has reported it, I'm assuming I'm getting some sort of conflict with another mod, but unfortunately the error doesn't mention any mods, I just know yours is involved from when it's happening.

[crash-2017-01-06_08.59.27-server.txt](https://github.com/WhiskyTangoFawks/Expedition/files/690714/crash-2017-01-06_08.59.27-server.txt)
[crash-2017-01-06_12.38.05-server.txt](https://github.com/WhiskyTangoFawks/Expedition/files/690716/crash-2017-01-06_12.38.05-server.txt)
[crash-2017-01-06_13.15.52-server.txt](https://github.com/WhiskyTangoFawks/Expedition/files/690712/crash-2017-01-06_13.15.52-server.txt)
[crash-2017-01-06_13.22.33-server.txt](https://github.com/WhiskyTangoFawks/Expedition/files/690711/crash-2017-01-06_13.22.33-server.txt)
[crash-2017-01-06_13.22.39-server.txt](https://github.com/WhiskyTangoFawks/Expedition/files/690715/crash-2017-01-06_13.22.39-server.txt)
[crash-2017-01-06_13.27.26-server.txt](https://github.com/WhiskyTangoFawks/Expedition/files/690713/crash-2017-01-06_13.27.26-server.txt)
[crash-2017-01-06_13.51.07-server.txt](https://github.com/WhiskyTangoFawks/Expedition/files/690717/crash-2017-01-06_13.51.07-server.txt)

**Comment by WhiskyTangoFawks** [comment]
I can only speculate on what's going on, given the logs don't reference my mod directly, but I did notice that cracked stone fracturing wasn't behind code that restricts it to running server side, when it probably should have been.  I've added a check to restrict it to the server, so when the next release comes out, see if it fixes the issue.

**Comment by WhiskyTangoFawks** [comment]
I suspect I've figured out what's happening, and got it sorted for the next release

**Comment by WhiskyTangoFawks** [comment]
New release is out, should solve this issue.
