### ISSUE TITLE
Incompatible with Amplified World TYpe: java.lang.ArrayIndexOutOfBoundsException: 16

### ISSUE THREAD

**Issue by mindofsiren** [WhiskyTangoFawks/Expedition#76]
Started getting this crash [crash-2017-01-14_18.23.29-server.txt](https://github.com/WhiskyTangoFawks/Expedition/files/706365/crash-2017-01-14_18.23.29-server.txt)

Not sure why its happening, just to note I am playing on an amplified world so that may be a contributing factor.

**Comment by WhiskyTangoFawks** [comment]
That is due to the amplified worlds- and it's exposed a bug in my world scanner.  I've got a fix, as well as some optimisation done now, that will go out with the next version whenever it ships.

**Comment by WhiskyTangoFawks** [comment]
New versions out with the fix for this.
