### ISSUE TITLE
High tick rate when exploring

### ISSUE THREAD

**Issue by darkphan** [WhiskyTangoFawks/Expedition#77]
From version 1.3.3 and up we get extremely high tick rate after a bit (seems to be triggered when we start to explore)

I have installed Naller's TickProfiler on my server to try to determine the tick lag and this is an example of the output:

`Profiling for 30 seconds in all worlds
[15:21:53] [TickProfiler/INFO] [TickProfiler]:

TPS: 0.033326667

             Single Entity | Time/Tick |     %

item.EntityItem 89,8,260:0 |    17.434 | 1.887

item.EntityItem 85,7,258:0 |    14.170 | 1.533

item.EntityItem 85,7,258:0 |    10.309 | 1.116

item.EntityItem 87,7,261:0 |     9.441 | 1.022

item.EntityItem 85,7,258:0 |     9.290 | 1.005

    Chunk | Time/Tick |      %

 0: 5, 16 |   641.643 | 69.438

 0: 5, 15 |   275.977 | 29.866

0: 17, 19 |     0.333 |  0.036

  0: 4, 6 |     0.321 |  0.035

 0: 10, 5 |     0.255 |  0.028

 All Entities of Type | Time/Tick |      %

  gameplay.StoneCrack |   830.020 | 89.823

      item.EntityItem |    89.452 |  9.680

    EntityMobChicken2 |     1.330 |  0.144

passive.EntityChicken |     1.300 |  0.141

    passive.EntityCow |     0.660 |  0.071

Average Entity of Type | Time/tick | Calls

       item.EntityItem |     0.328 |   273

     EntityWroughtnaut |     0.148 |     4

 common.EntityTortoise |     0.029 |     1

       EntityCrocoduck |     0.026 |     2

       EntityChameleon |     0.025 |     2`

As you can see the gameplay.StoneCrack is causing the bulk of the issues. This seems to go away when we use version 1.3.1 of the mod, so not sure if something changed with the way cracked blocks are handled in the world after that release or not.

(sorry about the formatting not sure the best way to paste that output lol)

**Comment by WhiskyTangoFawks** [comment]
The stone crack entity is the way I swapped how doing cracked stone- it's an entity that gets created when a player destroys a cracked stone block- it fractures the adjacent stone on a slight  time delay, then removes itself.  You shouldn't be getting it without first breaking a stone block.  Just to confirm, you're getting this behaviour withour breaking any blocks?

**Comment by darkphan** [comment]
That is correct it happens without breaking blocks

**Comment by WhiskyTangoFawks** [comment]
Well, after doing some profiling I've found that the the entities aren't behaving quite correctly in regards to removing themselves, which does lead to some ticking issues.  However- there's nothing I've found that would spawn them without a player breaking a cracked stone block (literally the only way the entity spawns is by the onBlockDestroyedByPlayer method in cracked stone).  Does this happen to be as part of a large modpack, particularly anything with some automation or that might otherwise break a block on it's own?

**Comment by darkphan** [comment]
It happens in a fresh world without any automation going etc. Do dungeons spawning in trigger cobble, sand, dirt etc to start falling?

**Comment by darkphan** [comment]
Just an update, seems the same issue happens in 1.3.1. Restarted the server and the tick rate stayed normal.

**Comment by WhiskyTangoFawks** [comment]
New version's out, should solve this issue completely.
