### ISSUE TITLE
WTFGameplay 'false' being ignored in WTFCore.cfg

### ISSUE THREAD

**Issue by skruis** [WhiskyTangoFawks/Expedition#8]
Just updated to the latest version available in Curse (1.10.2_Beta11.4.jar). I had previously set the line: 

    B:"Set to false to disable all gameplay tweaks for a vanilla gameplay experience.  This override ALL options set inside WTFGameplay.cfg"=false

After updating, all of the vanilla recipes were removed. If I went into WTFGameplay.cfg and set:

    B:"Remove recipes for vanilla tools (Requires Tinkers Construct to be installed)"=false

Restarted and the vanilla recipes were present again. I also noticed that "Home Scrolls" were enabled again thinking that maybe WTFGameplay.cfg was being partially ignored and that perhaps the one feature that disabled vanilla tools or the 'loot and crafting' section had been exempted from the gameplay disabling.

Please let me know if you need additional info.

*EDIT* Did some testing. It looks like it works as expected in Beta 10 (the version I originally upgraded from). I worked backwards from 11.4 and this behavior started in the original Beta 11 released on 9/6.

**Comment by WhiskyTangoFawks** [comment]
I've found what's causing those, and it's fixed for the next release.

Thanks for finding those.

**Comment by skruis** [comment]
No problem. Thanks for the quick fix!
