### ISSUE TITLE
Crash when disabling static deco blocks.

### ISSUE THREAD

**Issue by mindcloud69** [WhiskyTangoFawks/Expedition#83]
https://gist.github.com/mindcloud69/bb53a1e43fbe8b51afb523cfad3a0406

**Comment by WhiskyTangoFawks** [comment]
How did you disable deco static blocks, and what are you trying to achieve by doing so?

**Comment by mindcloud69** [comment]
I disabled all static blocks I didn't test one by one sorry.

**Comment by mindcloud69** [comment]
The same result with 1.3.6

**Comment by WhiskyTangoFawks** [comment]
Did you remove the cracked stone generation string from the ore config?

**Comment by mindcloud69** [comment]
no I did not. Should I have?

**Comment by WhiskyTangoFawks** [comment]
Yeah, I suspect that is why it has crashed.
