### ISSUE TITLE
Deco Blocks generating on the water in cave world

### ISSUE THREAD

**Issue by mindcloud69** [WhiskyTangoFawks/Expedition#84]
http://imgur.com/a/R0mrh

https://gist.github.com/mindcloud69/cf0fdf73a06da93ec10bc221753548bf

**Comment by WhiskyTangoFawks** [comment]
What version of the mod are you on?

**Comment by mindcloud69** [comment]
version 1.3.5 I see the new version that was released. I will try that and let you know if the problem still exists.

**Comment by mindcloud69** [comment]
1.3.6 Still happening

**Comment by WhiskyTangoFawks** [comment]
New version is going up that should prevent this from happening.
