### ISSUE TITLE
Ore Config Crash

### ISSUE THREAD

**Issue by WenXin20** [WhiskyTangoFawks/Expedition#85]
Expedition v1.3.6
Forge 2221
I get a crash whenever I add certain types of blocks to the background stones list, such as minecraft:clay@0 or mineralogy:amphibolite@0
[Crash Log](http://pastebin.com/Lpd6SgzE)

**Comment by WhiskyTangoFawks** [comment]
As per the instructions, a block has to be added to the stone registry before it can be used as a background block for ores.

**Comment by WenXin20** [comment]
Ok, that makes sense. I was using the ones I added from the stone registry config, but not the one that was actually being used. :D Thanks
Also, am I able to change the block registry name for the stones registry list yet?
