### ISSUE TITLE
Ardite generates in wrong dimension

### ISSUE THREAD

**Issue by WesCook** [WhiskyTangoFawks/Expedition#86]
The ardite config defaults to generating in the overworld.  Though it doesn't seem to in actuality.  Settings its dimension to -1 solves this.

Also a tiny issue that doesn't deserve its own bug report.  You have a typo in your lang file.  `tile.ubcSand.2.name=Shale Sand`

**Comment by WhiskyTangoFawks** [comment]
So, the issue is just a typo in the default config?

**Comment by WesCook** [comment]
Sorry, there's two issues.  I was just being lazy so I tacked the second one on.

1. Ardite is having the wrong dimension set in the default ore config file.
2. There's a typo in the English lang file for Shale Sand.

**Comment by WhiskyTangoFawks** [comment]
New version should have these corrected.

**Comment by WesCook** [comment]
Just to note, Shale Sand still has a typo.  It shows in game as Shale San.

https://github.com/WhiskyTangoFawks/Expedition/blob/master/1-9Forge/src/main/resources/assets/wtfcore/lang/en_US.lang#L50

Using latest version as of today (1.10.2_-1.5beta).
