### ISSUE TITLE
Limestone- lags

### ISSUE THREAD

**Issue by buddy3315** [WhiskyTangoFawks/Expedition#87]
I have noticed that when ever limestone is close by or I am looking at it the game FPS drop quite a bit. Makes low resource computers have trouble playing. Is the block at a higher resolution? I find that strange. Also noticed it comes with its own texture pack. Only limestone block seems to do this.

I'm running the game only on a onboard video card. (No external Video card installed) so I'm very sensitive to rendering issues.

I'm using a RTG mod with a few others as well. Also Optifine

**Comment by WhiskyTangoFawks** [comment]
None of the mods you've mentioned add limestone, nor does my mod add limestone.  Nor would a basic block cause the problems you're talking about.

For higher performance, make sure fancy blockstates are turned off (default is off) in the master config.

**Comment by buddy3315** [comment]
I am truely sorry as that was my mistake Yes you are correct! I just came back to delete this. I feel bad

**Comment by WhiskyTangoFawks** [comment]
No problem.  Let me know if there's anything else you need help with.
