### ISSUE TITLE
OutOfBoundsException: 16

### ISSUE THREAD

**Issue by yggdrasil75** [WhiskyTangoFawks/Expedition#90]
I have been having the following error in my minecraft for a while now: 
https://gist.github.com/yggdrasil75/2d2373f17502222377e57ad2c6dcf13d#file-crash-2017-01-28_18-58-34-server-txt

I do not know what causes this error, I have played with the mod and it only occurs when generating new terrain, which means that I can not get the cave biomes. I have tried without BoP and Farseek/Streams, but those should not have issues from what I read in your description of the mod.

**Comment by WhiskyTangoFawks** [comment]
what version of the mod are you on?

**Comment by yggdrasil75** [comment]
I am using 1.3.6.1

**Comment by WhiskyTangoFawks** [comment]
I'm having some trouble replicating the error- and thus I suspect it's an interaction with one of your other mods.  Are you able to replicate the crash with just WTF-Expedition on it's own?  And if not, which of the mods is causing the conflict?  It's not streams, as I use that in my own pack without issue.  BoP would be my prime suspect based on the crash report, but I can't figure out why it woudl do that, unless it's changing a fundamental world parameter, which as far as I know it doesn't.

**Comment by yggdrasil75** [comment]
I have tried to duplicate the error myself and every time get a different error. I found one where Quark's alternate stone generator caused crashes, which was fixed by disabling that, I then found an error with custom mob spawner, that appears to be fixed by resetting the config; I never deleted old biomes there. I am currently getting the following:

**Comment by MisterObvious25** [comment]
I can duplicate this error with only

forge-1.10.2-12.18.3.2209-universal.jar
placemod-3.8-1.10.2.jar
WTF-Expedition_1.10.2_v-1.4.jar
MCMultiPart-experimental-2.0.0_88-universal.jar

Crash sometimes occurs when creating a new world, but almost always when new chunks are generated and placemod places structures.

[Crash Rapport](http://pastebin.com/MYVD2sW1)
[From Create world to crash](http://pastebin.com/UfKjCS3F)

Removing placemod seems to help

**Comment by WhiskyTangoFawks** [comment]
I was able to duplicate it finally.  Fix will be out in 1.4.1

**Comment by ruyanve** [comment]
Same here... a couple of players are trapped in a crashing chunk. :(
Looking forward to the fix <3

**Comment by WhiskyTangoFox** [comment]
Oh, sorry about that.  I'm actually in the middle of a rebuild of the core architecture of the mod, so everything is kind of in pieces on the floor at the moment (playing around with the possibility of multi-threading or buffering some of my generation).  I *think* I might have a dev build I compiled after applying the fix, I'll check tonight, and if I didn't delete it I'll post a link here and you can test it out.

**Comment by WhiskyTangoFawks** [comment]
new version's out on curseforge
