### ISSUE TITLE
Amplified World issues still present.

### ISSUE THREAD

**Issue by mindofsiren** [WhiskyTangoFawks/Expedition#92]
I installed the new version but now there seems to be another crash, happened after around 10 minutes of playing. 
[crash-2017-01-30_15.03.00-server.txt](https://github.com/WhiskyTangoFawks/Expedition/files/740704/crash-2017-01-30_15.03.00-server.txt)

**Comment by WhiskyTangoFawks** [comment]
The new beta should prevent this issue.
