### ISSUE TITLE
Stone registry crash bug

### ISSUE THREAD

**Issue by EnderStar** [WhiskyTangoFawks/Expedition#93]
Hi, if i add a block with a name that isnt already in the stone registry the game crash on load with an outofbounds exeption 1 error, for example adding minecraft:grass@0 will result in a crash but adding minecraft:dirt@1 wont.
Thanks!
This happens with latest 1.3.6.1 for 1.10.2 without other mods.

**Comment by EnderStar** [comment]
I found what caused this, its setting null for the stone texture resource location of the new blocks, adding that fixes it :)

**Comment by WhiskyTangoFawks** [comment]
Yes, my generator isn't always capable of figuring out what other mod authors have done, so in many cases you have to manually enter that information.
