### ISSUE TITLE
Stone registry error adding wtfcore blocks

### ISSUE THREAD

**Issue by EnderStar** [WhiskyTangoFawks/Expedition#95]
Hi, adding a wtfcore block like wtfcore:oreSandGold@0 results in a crash, nullpointerexeption,
v 1.3.6.1 mc 1.10.2 
Thanks!

**Comment by WhiskyTangoFawks** [comment]
I can't do anything without a crash report.

Second, why are you trying to add an ore block to the stone registry?  There's no reason I can think of to do that.
