### ISSUE TITLE
Skeleton Mages spawn in blocks when coming from a spawner

### ISSUE THREAD

**Issue by Biochao** [WhiskyTangoFawks/Expedition#97]
First noticed this while going though a Roguelike Dungeon. Thought it was because of the custom spawners, but replacing it with a regular spawner has the same issue.
![2017-01-31_19 57 18](https://cloud.githubusercontent.com/assets/6515654/22491536/431401ee-e7f2-11e6-998f-e10b60fa7892.png)

**Comment by WhiskyTangoFawks** [comment]
It's an issue I'm aware of, and am working on an overhaul for my dungeon system, which should include a fix.

**Comment by WhiskyTangoFawks** [comment]
New versions going up now, shold solve the issue.
